### ISSUE TITLE
流量统计代码只允许纯js文本

### ISSUE THREAD

**Issue by tusik** [Licoy/wordpress-theme-puock#10]
头部和页脚只支持纯js文本么
像google analytics都需要引用外部js,直接把GA提供的代码扔进去就会移除掉所有的html标签,只剩下纯js代码

**Comment by Licoy** [comment]
考虑欠缺，已修复。

**Comment by tusik** [comment]
> 考虑欠缺，已修复。

但是在设置界面好像还并未修改,会自动去除html标签

**Comment by Licoy** [comment]
@tusik 修复了
