### ISSUE TITLE
在"SEO"设置中“流量统计代码”写入js后，浏览文章无法正常加载文章内容

### ISSUE THREAD

**Issue by iamsino** [Licoy/wordpress-theme-puock#108]
WordPress版本：5.8.3
主题版本号：2.0
PHP版本：7.2
问题阐述：
---------------
在"SEO"设置中“流量统计代码”写入js后，如cnzz的统计代码：
`<script type="text/javascript">document.write(unescape("%3Cspan id='cnzz_stat_icon_1******'%3E%3C/span%3E%3Cscript src='https://s9.cnzz.com/stat.php%*****D1%26show%3Dline' type='text/javascript'%3E%3C/script%3E"));</script>`
![image](https://user-images.githubusercontent.com/85120883/150117482-579c23f9-a464-4a33-96a4-d078c3832808.png)

访问首页是正常的，但是浏览文章无法加载文章内容，仅显示统计信息：
![image](https://user-images.githubusercontent.com/85120883/150117422-7f04b3d9-0dd9-4ede-9a82-b3c6db2d299b.png)

**Comment by Licoy** [comment]
@iamsino 我自己的站点也是放在这个里面，用了百度和谷歌的统计代码均没有问题呀

**Comment by Licoy** [comment]
暂无回复，有此类问题再开启，先关闭
