### ISSUE TITLE
在使用了代码高亮插件（Highlighting Code Block）后样式错乱

### ISSUE THREAD

**Issue by lzhbhlrPython** [Licoy/wordpress-theme-puock#117]
如题

测试链接:https://c9.g2024.cyez.site/2022/02/02/hello-world/

当天上午样式还是正常的……下午就出毛病了

**Comment by Licoy** [comment]
插件冲突，关闭插件即可

**Comment by lzhbhlrPython** [comment]
关闭插件使用原生代码仍然存在问题
QAQ

**Comment by Licoy** [comment]
@lzhbhlrPython 实际访问并没有关闭
