### ISSUE TITLE
编辑器中的html转义内容会在下次进入编辑器时自动转义

### ISSUE THREAD

**Issue by MociLSeng** [Licoy/wordpress-theme-puock#119]
WordPress版本：5.8.3
主题版本号：2.1
使用插件：WP Githuber MD
问题阐述：
---------------
在代码块中使用html标签，更新后的结果html标签会被渲染，比如
``` java
write("<p>123</p>");
```
效果：
write("
<p>123</p>
");

所以写成
write("&amp;lt;p&amp;gt;123&amp;lt;/p&amp;gt;");

但是下次进入编辑器就会变成
write("&lt;p&gt;123&lt;/p&gt;");

只有代码块会这样
不知是不是跟WP Githuber MD的兼容性问题

**Comment by Licoy** [comment]
@MociLSeng `WP Githuber MD`中貌似有关于转义设置的开关
