### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by aoyouer** [Licoy/wordpress-theme-puock#12]
感谢分享那么优秀的主题，不过我觉得手机上浏览时感觉还是有一点单薄，希望手机上显示的文章卡片中能显示一点文章的摘要/发布日期/标签等信息而不是仅仅一张图一个标题，还有就是如果能在手机上显示一下小工具就更好了。
另外，我觉得还可以加入回到页面顶部的固定按钮，像图里这样
![image](https://user-images.githubusercontent.com/32638818/94330716-8f0aa300-fff9-11ea-8778-a731a96ccc32.png)
这两个按钮分别是隐藏边栏和回到顶部。
再次感谢作者的分享。

**Comment by Licoy** [comment]
@aoyouer 感谢您的建议，关于您提到的几点，除了小工具之外其他都可以进行考虑，毕竟对于移动端的屏幕实在是太小了，不容易进行小工具的展示，谢谢。

**Comment by o1f** [comment]
可以在原文整个编辑按钮吗? 更新文章更方便些

**Comment by Licoy** [comment]
> 可以在原文整个编辑按钮吗? 更新文章更方便些

可以的
