### ISSUE TITLE
使用了外部图片的时候，首页加载缩略图加载不出来

### ISSUE THREAD

**Issue by zhanggaoxuan** [Licoy/wordpress-theme-puock#120]
WordPress版本：5.9
主题版本号：2.2
PHP版本：[选填]
问题阐述：
---------------
当正文使用了外部图片的时候（也就是使用了外链图片的时候），首页加载缩略图加载不出来。
预期：
当发现正文无图片的时候，默认使用缩略图，而不是判断有图又是外链图的时候，就加载不出缩略图

**Comment by Licoy** [comment]
@zhanggaoxuan 参考 #75
