### ISSUE TITLE
国内用户avatar头像加载不了，建议把默认的avatar头像换成本地图片

### ISSUE THREAD

**Issue by jsonhet** [Licoy/wordpress-theme-puock#125]
是否为已有功能：是/否
建议阐述：
未登录状态时顶部菜单栏会加载默认的avatar头像
`<img alt="登入" src="https://secure.gravatar.com/avatar/1522b2278fc0723f2de56d27928e1629?s=96&amp;d=mm&amp;r=pg" class="min-avatar">`
建议换成本地图片
---------------

**Comment by Licoy** [comment]
主题设置里面有切换gravatar头像源
