### ISSUE TITLE
一些功能上的意见

### ISSUE THREAD

**Issue by qffsy** [Licoy/wordpress-theme-puock#126]
是否为已有功能：否
建议阐述：
1推荐增加 代码插入功能 高亮
2侧边栏推荐增加 跟随页面滑动 一直显示侧边栏 要不文章太长侧边栏 一篇空白有些 单调（可设置开关）
3推荐cms首页也增加翻页功能或者是ajax翻页
4导航栏登录入口按键推荐增加 （ 登录 ）二字，单一头像按键有的人找不到
5后台 -主体设置-基本设置页面：文章转载说明 功能  此功能推荐可以使用html代码，方便文字较多时可以换行 特殊文字加粗等更多用法
---------------
以上为个人看法  仅供参考 如有不足之处 还望谅解

**Comment by Licoy** [comment]
部分采纳功能均已实现
