### ISSUE TITLE
“关于博主”小组件中如何上传博主头像

### ISSUE THREAD

**Issue by craii** [Licoy/wordpress-theme-puock#127]
添加“关于博主”小组件时，想要添加个人的头像。其中提示输入邮箱，但输入邮箱之后无法无效果。请问如何添加博主头像？为什么不做成和添加“关于博主”背景图一样，输入图片地址或上传就好？

**Comment by Licoy** [comment]
@craii 头像是基于[gravatar](https://en.gravatar.com/)提供的服务，你需要在其注册账户并上传设置您的头像

**Comment by craii** [comment]
建议在小工具设置时的提示文案可以描述一下

**Comment by Licoy** [comment]
> 建议在小工具设置时的提示文案可以描述一下

可以
