### ISSUE TITLE
正文内容底部相关推荐

### ISSUE THREAD

**Issue by ccgakki** [Licoy/wordpress-theme-puock#136]
是否为已有功能：是/否
建议阐述：
目前的底部文章相关推荐似乎并不是根据 标签或者分类 来推荐是吗？ 我觉得目前的推荐相关性好像并不大，似乎是随机的，每次刷新会改变，能否增加一个推荐文章选择机制，和推荐文章数量控制机制。

**Comment by rankment** [comment]
可以考虑用插件 Yet Another Related Posts， 如果要看着舒服，需要处理下显示

**Comment by Licoy** [comment]
是通过相同分类来推荐的
