### ISSUE TITLE
同一天发布的文章，在归档页面只显示最新一篇的日期,

### ISSUE THREAD

**Issue by Eveaz** [Licoy/wordpress-theme-puock#14]
求大佬指点一下，是我哪里设置有问题还是怎么？

### 问题描述如下：

> 比如我在今天28号发布了两篇文章，那么在文章归档页面就不显示第一篇的日期。

```
文章2 （28日）
文章1 （）
```
![QQ截图20201028213905](https://user-images.githubusercontent.com/51356521/97444131-c658d080-1966-11eb-9e51-29f323aa3511.png)
![QQ截图20201028213934](https://user-images.githubusercontent.com/51356521/97444166-ce187500-1966-11eb-8ca9-b747d85e368f.png)

> 如果我把第一篇文章改成27号就正常显示：

```
文章2 （28日）
文章1（27日）
```
![QQ截图20201028213954](https://user-images.githubusercontent.com/51356521/97444203-d7a1dd00-1966-11eb-97d3-06eb4b98e540.png)
![QQ截图20201028214019](https://user-images.githubusercontent.com/51356521/97444234-de305480-1966-11eb-8517-cb43d983ff45.png)

**Comment by Licoy** [comment]
好的

**Comment by Licoy** [comment]
已解决
