### ISSUE TITLE
列表缩略图使用微博图床时发现无法显示

### ISSUE THREAD

**Issue by jonexyz** [Licoy/wordpress-theme-puock#144]
是否为已有功能：是/否
建议阐述：原因是读取微博图床图片时被微博服务器拦截
---------------
解决方法； 文件路径  \inc\fun\core.php

修改函数 pk_get_img_thumbnail_src  添加如下代码

```
if(strpos($src,$_SERVER['HTTP_HOST'])===false){
        return $src;
    }

```
![图片](https://user-images.githubusercontent.com/31957754/170813281-fe9fd274-6bde-4785-b4af-ba6df2ceb47d.png)

**Comment by Licoy** [comment]
参考 #75
