### ISSUE TITLE
随机文章小工具在文章量大的前提下会拖慢打开速度

### ISSUE THREAD

**Issue by zhanggaoxuan** [Licoy/wordpress-theme-puock#146]
WordPress版本：6.0
主题版本号：2.4
PHP版本：8.0
问题阐述：
---------------

文章上万以后（我是10万），如果首页侧边栏用了随机文章小工具，网站打开需要20多秒。（在猜是不是遍历数据库导致的。开始以为是缓存或者加载了谷歌验证码，直到禁用了缓存和用国外服务器访问，发现都不行，就是慢，20多秒，删掉这个小工具，立马就基本上好了。）
可以考虑每10分钟从库里取几个放另外一个表。

**Comment by Licoy** [comment]
@zhanggaoxuan 10w+的文章想必大概是采集站点类型的吧，这种情况就不要使用随机文章了，如果需要使用请自行增加数据缓存策略及定时任务相关，此功能暂不做任何处理。
