### ISSUE TITLE
短代码嵌套问题

### ISSUE THREAD

**Issue by Creator2K** [Licoy/wordpress-theme-puock#147]
WordPress版本：6.0
主题版本号：2.4
PHP版本：[选填]
问题阐述：
使用回复可见登陆可见的短代码时，在中间嵌套文件下载，文件下载会失效
---------------

**Comment by Licoy** [comment]
@Creator2K 实测并没有出现问题，例如：

```
[login]

[download file='https://test.com/a.zip' size='12kb'][/download]

[/login]
```

**Comment by Creator2K** [comment]
[reply]
[download file='测试' size='22k']2knb.cn[/download]
[/reply]
![222](https://user-images.githubusercontent.com/44650774/172144358-ee1c10b8-2482-4495-a5c5-a6ce4bf02bc4.png)
