### ISSUE TITLE
新版编辑器中 增加短代码的按钮

### ISSUE THREAD

**Issue by blblank** [Licoy/wordpress-theme-puock#158]
是否为已有功能：否
建议阐述：新版编辑器中 增加短代码的按钮
---------------

**Comment by Licoy** [comment]
编辑器中是有短代码工具：

![image](https://user-images.githubusercontent.com/20410697/174508057-26929f9e-2c86-4fee-9ba9-d6c09ba031a1.png)

**Comment by blblank** [comment]
![QQ截图20220620090521](https://user-images.githubusercontent.com/38033532/174508394-718794a3-dc2c-4ccd-831e-d4778de22fe1.png)
是这个新的区块编辑器中没有主题的短代码按钮

**Comment by Licoy** [comment]
wp的新版编辑器中不建议使用短代码了，而是组件的方式。本主题暂没有计划对wp的新版编辑器进行支持，之后也只会更偏向于markdown的编辑的方向更新

**Comment by blblank** [comment]
哦，好的。
