### ISSUE TITLE
使用WP Editor.md在文章中使用链接图片时,会导致主页上文章的缩略图不显示。

### ISSUE THREAD

**Issue by xiaolilir** [Licoy/wordpress-theme-puock#16]
截图如下：
![截图.png](https://i.loli.net/2020/10/31/wYfviBW4aRXth2G.png)
后台console会有报错,跟进去截图如下:
![timthumb报错.png](https://i.loli.net/2020/10/31/JIzjXqQMNoi9Zmw.png)
求大佬帮忙看下，多谢

**Comment by Licoy** [comment]
@xiaolilir 你的图片链接是使用的图床的把，这个需要在 https://github.com/Licoy/wordpress-theme-puock/blob/aa07c1f62cf2720bd6de09efc83e71610b2895c2/timthumb.php#L133 进行添加一下域名白名单即可

**Comment by xiaolilir** [comment]
多谢提醒。已经解决。
