### ISSUE TITLE
请求增加主题页脚样式切换和主题字体切换设置

### ISSUE THREAD

**Issue by Unreal-System** [Licoy/wordpress-theme-puock#160]
- 是否为已有功能：是/否
- 建议阐述：
请求增加主题页脚样式切换
原有样式
![1](https://user-images.githubusercontent.com/31071269/177020961-c9a6dc39-c679-4418-b30b-806383c8a4e8.png)
换为同一行用8个`&nbsp;`分隔样式
![2](https://user-images.githubusercontent.com/31071269/177020963-2c8b569a-a6b0-46ab-895b-1aef839a7b24.png)

已从作者指定平台[购入字体](https://mianbaoduo.com/o/bread/Y5iZlw==)，希望能提供更换字体的设置而不是每次更新都要手动改

**Comment by Licoy** [comment]
这是固定的样式版权样式，对于页脚底部的内容设置可以在`主题设置`里面进行设置，除此之外这部分展不会做任何更新
