### ISSUE TITLE
请求提供主题字体链接位置设置

### ISSUE THREAD

**Issue by Unreal-System** [Licoy/wordpress-theme-puock#161]
- 是否为已有功能：否
- 建议阐述：
已从作者指定平台[购入字体](https://mianbaoduo.com/o/bread/Y5iZlw==)，希望能提供更换`字体链接位置`的设置而不是每次更新都要手动改

**Comment by Licoy** [comment]
主题设置中有自定义css，直接使用`important`属性覆盖即可，或者在顶部统计代码中执行写入`link`标签；另外那个字体本主题只是免费采用，并无任何言语说需要购入，也并未进行相关合作。
