### ISSUE TITLE
广告设置 如何添加 谷歌广告 百度联盟广告

### ISSUE THREAD

**Issue by jonexyz** [Licoy/wordpress-theme-puock#164]
- 是否为已有功能：是/否
- 建议阐述：富文本模式，无法添加 谷歌广告，百度广告，建议是广告设置取消富文本编辑器，如需要 用户自行编写 html 即可

**Comment by luteresa** [comment]
添加广告，是个实用功能，希望可以早点支持，谢谢

**Comment by Licoy** [comment]
![image](https://user-images.githubusercontent.com/20410697/187009000-df71c68a-282a-4c98-9547-6ac60678e961.png)

在广告的编辑中选择【文本】模式即可输入HTML
