### ISSUE TITLE
已登录提交评论提示无效验证码

### ISSUE THREAD

**Issue by ZhaohuiWu** [Licoy/wordpress-theme-puock#168]
- 主题版本号：2.5.3
- WordPress版本：6.0.1
- PHP版本：5.6
- 问题阐述：评论时提示无效验证码

**Comment by Licoy** [comment]
请先确认是否开启session支持

**Comment by ZhaohuiWu** [comment]
开启了，但是还是不行。
并且在你的网站（https://licoy.cn/3590.html）上试了一下也不可以评论。
![image](https://user-images.githubusercontent.com/25701477/183298216-5ca33949-8d95-4dad-85fe-daeb0d054959.png)
这个时火狐浏览器控制台的报错
![image](https://user-images.githubusercontent.com/25701477/183298251-7f055968-fdb4-4b11-9b39-bfb13e364497.png)
这个是谷歌浏览器控制台的报错
![image](https://user-images.githubusercontent.com/25701477/183298353-cb805f3d-cbd3-4aa3-a84f-5ff07b059059.png)

**Comment by Licoy** [comment]
![image](https://user-images.githubusercontent.com/20410697/183319901-52400064-de86-4ab2-be88-5cbd0383c421.png)

我的网站上可以呀

**Comment by Licoy** [comment]
你应该是登录了，然后再提交评论对吧，确实存在这个问题

**Comment by ZhaohuiWu** [comment]
之前的确是先登录后再提交的评论，但是试了一下即使不登录也不可以提交评论。
谷歌浏览器版本：版本 104.0.5112.81（正式版本） （64 位）
![image](https://user-images.githubusercontent.com/25701477/183323052-fb83ddee-d9ec-4255-874d-2c7ee8887348.png)
