### ISSUE TITLE
开启wp super cache缓存下文章页面浏览量统计显示异常。

### ISSUE THREAD

**Issue by Eveaz** [Licoy/wordpress-theme-puock#17]
图1、大佬你的博客，文章页。
![Snipaste_2020-10-31_20-39-37](https://user-images.githubusercontent.com/51356521/97779545-aec55600-1bb9-11eb-9cc4-d9ad422473af.png)
图2、登陆状态下，前台文章页面，主题设置不开启浏览量异步加载。
![Snipaste_2020-10-31_20-40-17](https://user-images.githubusercontent.com/51356521/97779596-08c61b80-1bba-11eb-9cf6-714d9a33ba2d.png)
图3、登陆状态下，开启浏览量异步加载。“次阅读次阅读”这几个字会在加载的一瞬间出现，然后消失，只剩下浏览量的图标和数字。
![QQ截图20201031205004](https://user-images.githubusercontent.com/51356521/97779712-d36dfd80-1bba-11eb-8e9a-73dadddc1e1a.png)
图4、禁用wp super cache之后，非登陆状态下，不开启浏览量异步加载。
![QQ截图20201031205303](https://user-images.githubusercontent.com/51356521/97779755-38c1ee80-1bbb-11eb-88bf-6909e7df996f.png)
图5、禁用wp super cache之后，登陆状态下，不开启浏览量异步加载。
![QQ截图20201031205521](https://user-images.githubusercontent.com/51356521/97779808-93f3e100-1bbb-11eb-8e6b-a9edc630e709.png)
图6、禁用wp super cache之后，登陆状态下，开启浏览量异步加载。
![QQ截图20201031205724](https://user-images.githubusercontent.com/51356521/97779847-d74e4f80-1bbb-11eb-8522-f15f7d2e885a.png)
图6、禁用wp super cache之后，非登陆状态下，开启浏览量异步加载。
![QQ截图20201031205950](https://user-images.githubusercontent.com/51356521/97779896-1aa8be00-1bbc-11eb-8a5c-6f39054f43ee.png)
图7、不管禁用wp super cache与否，在非登陆状态下，开启浏览量异步加载，F12查看都会有
![Snipaste_2020-10-31_20-40-46](https://user-images.githubusercontent.com/51356521/97779921-43c94e80-1bbc-11eb-961f-bc1f7c5924d0.png)
只要主题设置开启浏览量异步加载，不管登陆与否，不管是否开始wp super cache， “次阅读次阅读”这几个字会在加载的一瞬间出现，然后消失，只剩下浏览量的图标和数字。

**Comment by Licoy** [comment]
好的，待查明之后进行修复
