### ISSUE TITLE
更新版本后2.6.1. 打开控制台查看TDK信息没了

### ISSUE THREAD

**Issue by echome123** [Licoy/wordpress-theme-puock#179]
- 主题版本号：2.6.1
- 问题阐述：升级之后，seo出现收录下降，查看了一下控制台代码，发现TDK信息，只有title在，description和keywords都没了，后台确定已经配置好了，并且也保存完整了。
- 接着去看了看作者的博客，依然一样，也是空的，如下：
```
<meta name="keywords" content="">
 <meta name="description" content="">
```
麻烦核实，谢谢

**Comment by Licoy** [comment]
下个版本修复
