### ISSUE TITLE
首页显示了11篇文章，其中三篇是置顶文章，最后一行卡片位置有空

### ISSUE THREAD

**Issue by rankment** [Licoy/wordpress-theme-puock#181]
- 主题版本号：2.6.2
- WordPress版本：6.0.2
- PHP版本：[选填]7.4.30
- 问题阐述：

![image](https://user-images.githubusercontent.com/113095229/190901473-97024911-41f1-45ea-8714-4a18f2ad66db.png)

**Comment by rankment** [comment]
置顶文章为2篇时，不会出现这种情况

**Comment by Licoy** [comment]
主题设置-首页最新文章数量
