### ISSUE TITLE
显示点赞异常

### ISSUE THREAD

**Issue by Yichende** [Licoy/wordpress-theme-puock#187]
- 主题版本号：2.6.2
- WordPress版本：6.0.2
- PHP版本：[选填]
- 问题阐述：显示点赞异常
- 参考网站: blog.yichend.top

**Comment by Licoy** [comment]
你的那个访问点赞接口返回的是主页内容，不知道是否有其他什么插件影响了此操作

**Comment by Yichende** [comment]
我把插件都重新关掉了也是一样的，不清楚是什么问题，还有github和码云的第三方登录也用不了，点进去后就显示白屏

**Comment by Licoy** [comment]
这个应该是你自己配置的问题，我这边两个站点都没有问题

**Comment by 3150675236** [comment]
你是用子目录运行的吗，可以到wordpress-theme-puock-2.8.4/assets/dist/js/puock.min.js找到那个错误区块改一下目录
