### ISSUE TITLE
如何更改英语语言？

### ISSUE THREAD

**Issue by ntccloud** [Licoy/wordpress-theme-puock#193]
- 是否为已有功能：是/否
- 建议阐述：

如何更改英语语言？
我找不到任何东西可以切换到英语。
帮我！

**Comment by Licoy** [comment]
本主题对于英文的支持暂不完全（已经支持的部分只需要将你的WP版本更改为英文即可，会自动转换，如果显示为中文则代表此部分暂未翻译）
