### ISSUE TITLE
上传主题后点启用报错

### ISSUE THREAD

**Issue by HelloMusician** [Licoy/wordpress-theme-puock#194]
- 主题版本号：2.6.4
- WordPress版本：6.0.3
- PHP版本：7.3
- 问题阐述：通过WordPress外观-主题上传源代码压缩包，之后点启用界面跳转报错：
- Parse error: syntax error, unexpected ':', expecting '{' in /www/wwwroot/39.105.44.75/wp-content/themes/wordpress-theme-puock-master/inc/fun/oauth.php on line 134

请求方法: GET
状态代码: 500 Internal Server Error
远程地址: 127.0.0.1:7890
引用者策略: strict-origin-when-cross-origin

**Comment by Licoy** [comment]
@HelloMusician 应该是PHP版本太低了，建议7.4+，因为`134`行使用了新语法

**Comment by HelloMusician** [comment]
谢谢，我把php升级到7.4版本重新部署了一下就好了

憧憬Licoy ***@***.***> 于2022年10月21日周五 09:21写道：
