### ISSUE TITLE
启用子主题后部分功能失效

### ISSUE THREAD

**Issue by cstg04** [Licoy/wordpress-theme-puock#195]
我用的是puock的子主题，用子主题时发现有一些问题，比如说在经典编辑器里“添加表情”和“添加短代码”是无效的（这个是迫切想解决的问题），还有就是修改站点主色调也没用，颜色不会变，还有更新也会出问题。是要复制什么文件到子主题里去吗？（不懂代码orz）

**Comment by cstg04** [comment]
添加短代码按钮无效的问题解决了（）突然想起看看控制台

**Comment by Licoy** [comment]
没有试过子主题，等有空看看
