### ISSUE TITLE
在某些分辨率下菜单栏会出现bug？

### ISSUE THREAD

**Issue by XxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxX0** [Licoy/wordpress-theme-puock#209]
- 主题版本号：
- WordPress版本：https://licoy.cn/
- PHP版本：[选填]https://licoy.cn/
- 问题阐述：用的演示站
- 宽度在1200px-992px之间，菜单栏不正常
- https://s1.ax1x.com/2022/11/10/zphVW4.png
- https://s1.ax1x.com/2022/11/10/zpheSJ.png

**Comment by Licoy** [comment]
不是不显示，因为菜单过长而又未达到移动版本的宽度便错位了：
![image](https://user-images.githubusercontent.com/20410697/201094479-88058c4c-9146-4ec2-a218-8b3ccaf352af.png)

后续版本会做相关优化处理
