### ISSUE TITLE
大佬左上角会有很奇怪的"感叹"图标，不知道是为什么，详细见下图

### ISSUE THREAD

**Issue by xiaolilir** [Licoy/wordpress-theme-puock#21]
![1605165237_1_.png](https://vip2.loli.net/2020/11/12/ncqQoAiS5hJd2Ir.png)
## 就是下面这些元素导致的
![1605165526_1_.png](https://vip1.loli.net/2020/11/12/gHY9KWTw8dCNzbO.png)

**Comment by Licoy** [comment]
@xiaolilir 看一下你的后台菜单或其他插件是不是配置了什么，主题中没有用到关于`csz-about-l`这个图标字体

**Comment by xiaolilir** [comment]
> @xiaolilir 看一下你的后台菜单或其他插件是不是配置了什么，主题只有在footer.php以及下载短代码中用到了`czs-about-l`

@Licoy 多谢大佬的提示 已经解决。
