### ISSUE TITLE
页面有宽幕视频，页面显示异常

### ISSUE THREAD

**Issue by lz732895965** [Licoy/wordpress-theme-puock#213]
页面有宽幕视频，页面显示异常。详见https://www.one21.cn/%e5%bc%80%e5%9c%ba%e6%b2%a1%e6%9c%89%e9%80%80%e8%b7%af%ef%bc%8c%e4%ba%ba%e7%94%9f%e6%b2%a1%e6%9c%89%e8%90%bd%e5%b9%95/

**Comment by Licoy** [comment]
下个版本中会修复，此部分已经修复了只是还没发布版本
