### ISSUE TITLE
友情链接填写了描述，但鼠标悬停链接上方时，描述内容不显示，反而显示连接名称。

### ISSUE THREAD

**Issue by cat44444** [Licoy/wordpress-theme-puock#217]
- 主题版本号：
- WordPress版本：6.1.1
- PHP版本：8.1
- 问题阐述：友情链接填写了描述，但鼠标悬停链接上方时，设置的描述内容不显示，反而用链接名称代替了描述内容。

**Comment by Licoy** [comment]
那个是显示内容标题没错，描述的话是需要填写在`备注`里面

![image](https://user-images.githubusercontent.com/20410697/206720831-ab50dfb7-4c3d-474b-8f21-b3f131ad849f.png)

**Comment by cat44444** [comment]
我又试了一下把描述写在备注里，但鼠标悬停在链接上时显示的还是名称，没有显示备注的内容

**Comment by Licoy** [comment]
描述在悬浮的时候不会被显示，悬浮只会显示标题，描述只会显示在此处：
![image](https://user-images.githubusercontent.com/20410697/206726402-2ad4fe7b-5d52-417f-8e58-3fd2872616ad.png)

**Comment by cat44444** [comment]
感谢解答
