### ISSUE TITLE
后台全局禁止使用REST API功能建议

### ISSUE THREAD

**Issue by echome123** [Licoy/wordpress-theme-puock#218]
- 是否为已有功能：是
- 建议阐述：目前禁止使用REST API是完全禁止了所有的API接口通信，导致后台编辑器功能无法使用，可否修改策略为，关闭REST API后，只禁用游客的权限，保证已登录的管理员不受影响

**Comment by Licoy** [comment]
你可以关闭禁用，在主题设置中有

**Comment by Licoy** [comment]
已增加开关选项
