### ISSUE TITLE
导航栏下拉菜单的间距太大了

### ISSUE THREAD

**Issue by Workear34** [Licoy/wordpress-theme-puock#219]
- 是否为已有功能：是
- 建议阐述：导航栏上的下拉菜单的间距过大，一旦项目变多就会占屏幕很大一块，建议调小点
就像这样：
![image](https://user-images.githubusercontent.com/99064442/207556741-8d260b49-5c46-4f02-878d-4244a0900013.png)
（修改了一下来测试）

**Comment by Licoy** [comment]
不建议添加如此之多的二级菜单，太小则会在布局上产生违和感，暂不会进行相关处理
