### ISSUE TITLE
【多分类显示BUG】同一篇文章属于多个分类的时候，这篇文章内容展示的时候无法显示多个分类。

### ISSUE THREAD

**Issue by Arisono** [Licoy/wordpress-theme-puock#22]
**【Bug1】同一篇文章属于多个分类的时候，这篇文章内容展示的时候无法显示多个分类。**
![image](https://user-images.githubusercontent.com/8653027/99498524-91aec680-29b2-11eb-8ce8-b9654ceb22cb.png)

**【Bug2】点击进入，该文章的第二个分类文章目录下，无法正确显示。显示的是第一个文章分类。**
![image](https://user-images.githubusercontent.com/8653027/99498689-d4709e80-29b2-11eb-987d-f79758f4341b.png)

**我的网站地址**：[http://www.yundashi168.com/sharing/plugins-wp/](http://www.yundashi168.com/sharing/plugins-wp/)

希望作者能在下个版本能解决下。

**Comment by Licoy** [comment]
好的，目前的功能设计就是只显示一个分类，感谢反馈

**Comment by Arisono** [comment]
楼主，你这主题做的很优秀。请问自己开发wp主题需要从哪里开始，有什么技能点学习路线图吗，能否指点一二？非常感谢，我想自己开发wp主题。

**Comment by Licoy** [comment]
@Arisono 可以参考https://www.kancloud.cn/jabber/wordpress/296767

**Comment by Arisono** [comment]
谢谢了，我是java开发，业余学习php，就是为了学wp
