### ISSUE TITLE
菜单栏按钮图标点击没有反应

### ISSUE THREAD

**Issue by Yichende** [Licoy/wordpress-theme-puock#223]
- 主题版本号：2.7.0
- WordPress版本：6.1.1
- PHP版本：[选填]
- 问题阐述：有一段时间没看网站了，更新主题到2.7.0版本后发现右上角的搜索图标点击没有反应，切换高亮以及暗夜的图标同样点击没有反应，是不是调试的时候忘记把返回的 js 调回去了。
- 网址：http://blog.yichend.top/

**Comment by Licoy** [comment]
@Yichende 我访问测试是好的呀，如果出现点击不动大概是插件冲突了，把插件一个个关闭试试就知道了

**Comment by Yichende** [comment]
我试试吧，好像是有个js文件没加载进去
