### ISSUE TITLE
下载文件的简码，和插件里的“下载管理”插件冲突了

### ISSUE THREAD

**Issue by jiffish** [Licoy/wordpress-theme-puock#224]
- 主题版本号：2.7
- WordPress版本：6.11
- PHP版本：[选填]
- 问题阐述：安装了一个下载插件：“Download `Monitor”，结果，这个插件插入的简码是类似于[download `id="283"]`，但是最终效果没有呈现出来，而是主题主题自带的短码效果。主题自带的文件下载短码是[download file='xxx.zip' size='12MB']文件地址[/download]`  。 这个有办法改吗，主题自带的文件下载短码可以设置个关闭按钮吗？ 或者css仿一个文件下载站的下载样式

**Comment by Licoy** [comment]
只能你自行屏蔽主题内的`download`短代码
