### ISSUE TITLE
建议中文格式化（文案排版）不对链接进行处理

### ISSUE THREAD

**Issue by cstg04** [Licoy/wordpress-theme-puock#225]
- 是否为已有功能：否
- 建议阐述：
有些链接可能会存在中文，而中文格式化功能就会在链接里的中文前加空格（比如 ”www.baidu.com/百度” 会被改成 ”www.baidu.com/ 百度” ），从而导致链接失效。

**Comment by Licoy** [comment]
建议中文使用urlencode后的网址
