### ISSUE TITLE
希望可以增加自定义单栏、双栏选项

### ISSUE THREAD

**Issue by ssjiaaaron** [Licoy/wordpress-theme-puock#228]
- 是否为已有功能：否
- 建议阐述：个别页面在不启用侧栏时，页面内容会偏向一边，不是很美观，希望可以增加自定义单栏、双栏的选项，谢谢！

**Comment by Licoy** [comment]
“页面内容会偏向一边”是什么意思，给个示例

**Comment by ssjiaaaron** [comment]
这个应该是我看错了，发错了，谢谢！
