### ISSUE TITLE
timthumb好像对.webp格式不支持

### ISSUE THREAD

**Issue by Steady-WJ** [Licoy/wordpress-theme-puock#231]
- 主题版本号： v2.7.1
- WordPress版本：6.1.1
- PHP版本：PHP8.0
- 问题阐述：timthumb好像对.webp格式不支持
- 问题原因：AMH环境默认GD组件未编译WEBP
- 已解决

**Comment by Licoy** [comment]
这不是懒加载的问题，而是图片资源加载失败，经过测试在本地环境和线上环境都可以渲染webp的缩略图：
https://licoy.cn/wp-content/themes/puock/timthumb.php?w=400&h=200&a=&zc=1&src=https://licoy.cn/wp-content/uploads/2023/01/kkk_webp.webp
请检查您的环境，开启gd或gd2等图片相关处理的扩展

**Comment by Steady-WJ** [comment]
GD webp没编译 我重新编译解决了

**Comment by Steady-WJ** [comment]
解决方案：
apt-get install -y libwebp-dev

sed -i 's/--with-freetype/--with-webp --with-freetype/' /root/amh/modules/php-8.0/AMHScript

amh php-8.0 uninstall
amh php-8.0 install
