### ISSUE TITLE
V2.7.2版本页首页尾快捷按钮失灵

### ISSUE THREAD

**Issue by luteresa** [Licoy/wordpress-theme-puock#239]
- 主题版本号：v2.7.2
- WordPress版本：6.1.1
- PHP版本：[选填]
- 问题阐述：所有页面，拉到页首，页尾的快捷键失灵，还有页面扩展到整个区域的按钮也没反应

**Comment by Licoy** [comment]
亲测没有，检查是否有插件冲突导致jQuery无法使用

**Comment by luteresa** [comment]
测试过，不确定是哪个插件冲突导致，所以来这里请教。我的站是https://www.daodaodao123.com/

**Comment by Licoy** [comment]
插件全部关闭，然后再一个个开启尝试就可以知道是哪一个

**Comment by Licoy** [comment]
或者是你的主题版本是存在问题的，重新下载安装一下主题即可，主题设置数据不会被清除的

**Comment by luteresa** [comment]
WP Editor.md，Table of Contents Plus关闭就可以了.
但是markdown是我必用的插件啊，这个有更好解决方案吗；

**Comment by Licoy** [comment]
目前主题对 [githuber-md](https://github.com/terrylinooo/githuber-md) 兼容比较好，可以试试

**Comment by luteresa** [comment]
好的，我换成了githuber-md。谢谢
另外，开启这个插件Table of Contents Plus，Puock的按钮也会失效

**Comment by Licoy** [comment]
js冲突，你的前端所有js相关操作都无法使用

**Comment by Licoy** [comment]
760487a4 已兼容

**Comment by luteresa** [comment]
更新到v2.7.4.2，已经OK了，谢谢

**Comment by luteresa** [comment]
发现一个新问题，代码块自动在末尾另起一行加了个”Copy“
版本：v2.7.4.2

**Comment by Licoy** [comment]
有问题新开issue，附上截图，此issue关闭
