### ISSUE TITLE
【功能建议】首页可以选择文章列表和卡片展示，分类和标签下的文章，是否也可以单独支持设置卡片和列表展示。

### ISSUE THREAD

**Issue by Arisono** [Licoy/wordpress-theme-puock#24]
【功能建议】首页可以选择文章列表和卡片展示，分类和标签下的文章，是否也可以单独支持设置卡片和列表展示。

就是首页我想要列表展示。某一个分类和标签下的文章想要卡片展示。想灵活一点。不想全部是列表展示和全部是卡片展示。

**Comment by Licoy** [comment]
这个目前暂无计划
