### ISSUE TITLE
关于更新和评论区的建议

### ISSUE THREAD

**Issue by SummerAfternoon** [Licoy/wordpress-theme-puock#245]
- 是否为已有功能：否
- 建议阐述：

1. 在线更新的时候每次解压都是不同的，后面带了版本号，与已经安装的安装目录里的文件夹名称不一致，导致在线更新失败，只能手动更新。
2. 评论区好像似乎不能匿名评论，在后台设置了也不行。同时希望可以选择是否加载emoji，还是不希望有emoji。谢谢( ͡• ͜ʖ ͡• )

**Comment by Licoy** [comment]
1. 首次安装应该去手动更新主题的目录名字，后续则会进行直接更新迭代，wordpress是根据主题目录下的style.css中的名称为唯一标识来区分的。
2. 匿名不会考虑支持，twemoji作为主题的默认也是唯一的表情，目前不考虑开关选项。
