### ISSUE TITLE
支持纯英文？

### ISSUE THREAD

**Issue by wonderfulsuccess** [Licoy/wordpress-theme-puock#248]
wordpress 已经设置为 English，网站内部还算是有一些汉字，没有修改入口，比如文章末尾的“正文完”。能都改成英文的吗？
<img width="989" alt="Screenshot 2023-01-17 at 15 22 43" src="https://user-images.githubusercontent.com/7629820/212834797-ae429a51-79cd-45a9-87d8-310e12043ac7.png">

**Comment by Licoy** [comment]
完全国际化支持预计在v3.0之前的版本完成，参考 #201
