### ISSUE TITLE
与Code Black Pro插件冲突

### ISSUE THREAD

**Issue by lovesans** [Licoy/wordpress-theme-puock#254]
之前发布的文章是用Code Black Pro插件显示的代码块,换了主题后代码展示都错位了
主题设置里没有找到相关的开关,除了一条一条改之外还有其它方法吗?
![2023-01-22 00 47 25](https://user-images.githubusercontent.com/7107081/213877555-b4ff9276-be78-4d48-aee1-e362c08e3502.png)

**Comment by Licoy** [comment]
后续可以加上关闭主题本身的代码高亮功能

**Comment by ikcro** [comment]
遇见同样的问题，难受啊，这几乎没办法改了，代码太多了，请问有什么快速禁止主题代码高亮的方法吗
