### ISSUE TITLE
Asgaros论坛显示不全

### ISSUE THREAD

**Issue by TSaltedfishKing** [Licoy/wordpress-theme-puock#26]
![捕获](https://user-images.githubusercontent.com/60768370/100310369-fdfb7c80-2fe7-11eb-8913-de53fb0b84fc.PNG)
插件地址:https://wordpress.org/plugins/asgaros-forum/

**Comment by Licoy** [comment]
@TSaltedfishKing 目前未对此插件进行适配

**Comment by TSaltedfishKing** [comment]
嗯
