### ISSUE TITLE
跟备案要求冲突

### ISSUE THREAD

**Issue by luteresa** [Licoy/wordpress-theme-puock#262]
今天接到阿里云电话，个人网站不允许出现“赏”字，这个可以改成“赞”，或者开放使用者定制吗。
另外：puock主题如何修改备案信息？

**Comment by Licoy** [comment]
备案信息都是加载全局底部内容区域的，在`脚本与样式`选项里面，关于`赏`字之后会使用icon

**Comment by marvelousph** [comment]
这个赏字是咋回事，有详细的通知内容没

**Comment by luteresa** [comment]
阿里电话通知的，个人网站不能有打赏，收款二维码。

**Comment by Licoy** [comment]
你直接后台关闭这个功能就可以了 @luteresa

**Comment by Licoy** [comment]
ce010545 已优化
