### ISSUE TITLE
Cron重新计划事件时出现错误

### ISSUE THREAD

**Issue by CryingObsidian-CO** [Licoy/wordpress-theme-puock#264]
我想问一下
**[01-Feb-2023 10:45:00 UTC] Cron 重新计划事件时出现错误，钩子名称：puc_cron_check_updates_theme-wordpress-theme-puock-2.7.4.2，错误代码：invalid_schedule，错误消息：事件计划不存在。，数据：{"schedule":"every6hours","args":[],"interval":21600}**
这个是因为我设置错误还是什么原因呢，它产生了大量的日志文件，让我在Debug的之后很难找到真正的错误信息

**Comment by miniwater** [comment]
Puock主题配置-资源与更新-主题在线更新源-Github-保存
好像就可以了

**Comment by CryingObsidian-CO** [comment]
> Puock主题配置-资源与更新-主题在线更新源-Github-保存 好像就可以了

好的，我过几天去试试，谢谢

**Comment by typ431127** [comment]
防火墙会导致请求403，waf防火墙会导致这个问题
