### ISSUE TITLE
幻灯片选图时无法加载媒体库

### ISSUE THREAD

**Issue by SelfEnough** [Licoy/wordpress-theme-puock#265]
- 主题版本号：2.7.4.2
- WordPress版本：6.0
- PHP版本：[选填]7.4
- 问题阐述：幻灯片选图时无法加载媒体库
![image](https://user-images.githubusercontent.com/36906472/216755116-4cfc872d-33c1-46ae-9656-cf4822c4ed3c.png)
并没有目录权限问题，在后台管理的媒体库中 可以浏览上传图片，
![image](https://user-images.githubusercontent.com/36906472/216755163-d18f0f58-272e-4e34-af45-26745cafdac3.png)

**Comment by Licoy** [comment]
使用f12看看网络请求，是不是请求出现429

**Comment by hausen1012** [comment]
你这个后台怎么不一样

**Comment by BigdataZjk** [comment]
> 同样遇到，把content_type改下就好了，控制台可以
> 
> ```
> jQuery.ajaxSetup({
>     contentType: "application/x-www-form-urlencoded; charset=UTF-8"
> });
> ```
> 
> 永久修改的话是，把/wp-content/themes/puock/assets/dist/setting/index.js里面删去",window.jQuery.ajaxSetup({contentType:"application/json; charset=utf-8"})"

默认是application/x-www-form-urlencoded
