### ISSUE TITLE
代码块在末尾自动添加Copy

### ISSUE THREAD

**Issue by luteresa** [Licoy/wordpress-theme-puock#267]
- 主题版本号：V2.7.4.2
- WordPress版本：WordPress 6.1.1
- PHP版本：[选填]
- 问题阐述：代码块会在末尾自动添加copy
- 比如正常显示
git config --list   //查看当前配置

实际显示：
git config --list   //查看当前配置Copy

**Comment by Licoy** [comment]
截图看看，另外检查你的插件是否有相关代码高亮的影响

**Comment by Licoy** [comment]
使用
```html
<pre><code></code></pre>
```
包含起来即可，记住记得转义
