### ISSUE TITLE
【BUG反馈】文章第一次加载的时候，局部插件的样式资源文件没有加载

### ISSUE THREAD

**Issue by Arisono** [Licoy/wordpress-theme-puock#27]
博客地址：http://www.yundashi168.com/42.html

在博客列表页面[http://www.yundashi168.com](http://www.yundashi168.com)，点击这篇文章的时候，文章第一次加载的时候，局部插件的样式资源文件没有加载，导致文章目录显示有问题。【刷新浏览器之后，显示正常】
**我这里是文章目录页面插件第一次显示有问题，需要刷新浏览器才能正常显示**。
浏览器简单调试看了下，点击文章第一次加载，插件的资源文件js，css等文件没有加载，只有刷新当前浏览器，才会加载相关样式资源文件。求帮忙解决问题。

【**BUG出现，必须从博客文章列表页面点击文章进入，才会出现**】

**Comment by Licoy** [comment]
@Arisono 因为使用了无刷新加载，需要给对应重复加载的静态资源标签加上data-instant属性，或者关闭无刷新加载

**Comment by Arisono** [comment]
非常感谢楼主的回复，我去解决下问题
