### ISSUE TITLE
点赞 打赏的设置  更显眼的建议

### ISSUE THREAD

**Issue by liu95413** [Licoy/wordpress-theme-puock#273]
- 是否为已有功能：是/否
- 建议阐述：现有的点赞  打赏   也太婉约了，图标又小，别人不一定注意，不一定看得懂，还有分享，这个图可以参考参考，文章下面搞个大的点赞  打赏（喜欢）  。当然，个人见解，仅当参考
![image](https://user-images.githubusercontent.com/117451527/222703997-8b022924-f960-4078-bcd6-0d7e98ed9fe3.png)

**Comment by Licoy** [comment]
现在的可以了，太亮了反而有点故意引导了
