### ISSUE TITLE
nginx quic(http3)协议缩略图伪静态 无法加载400

### ISSUE THREAD

**Issue by ylwzbk** [Licoy/wordpress-theme-puock#274]
- 主题版本号：V2.7.5
- WordPress版本：6.1.1
- PHP版本：[选填] 8.1
- 问题阐述：nginx 在http3 协议下 开启了缩略图伪静态 功能 blog的缩略图会无法加载并400 ，关闭http3 或关闭缩略图伪静态正常

timthumb/w_280/h_160/q_90/zc_1/a_c/aHR0cHM6Ly95dW4ueWx3ei5jYy9ibG9nLzIwMjIvMDQvYmcyMDE4MDIwOTAxLnBuZw.png
[HTTP/3 400 Bad Request 38ms]
状态400Bad Request
版本HTTP/3
传输1.44 kB（大小 1.30 kB）
Referrer 策略strict-origin-when-cross-origin
请求优先级Low

**Comment by Licoy** [comment]
可以试试关闭缩略图伪静态

**Comment by ylwzbk** [comment]
关闭伪静态没用 ，好像是不支持http3协议  在H2 协议下就没事

**Comment by Licoy** [comment]
或许是不支持http3，后续验证处理一下
