### ISSUE TITLE
缩略图在获取外链图片时出现错误

### ISSUE THREAD

**Issue by Nnicoleyeah** [Licoy/wordpress-theme-puock#275]
- 主题版本号：v2.7.5
- WordPress版本：6.1.1
- PHP版本：[选填]7.4
- 问题阐述：
缩略图在获取外链图片时出现错误，该如何解决，或者有什么方法可以替换掉现有的timthumb而使用插件处理缩略图
![9d67acdeb52d07d7bdeaae5bad4fd31](https://user-images.githubusercontent.com/87277308/222944368-2c29980b-d0ec-44a2-bbc6-10811bac12f7.png)

**Comment by Licoy** [comment]
你可能开启了缩略图伪静态，试试关闭，如果还不行就看一下PHP的错误日志，或者直接访问这个资源URL

**Comment by Nnicoleyeah** [comment]
缩略图伪静态未开启。由于设置了防盗链，无法直接访问URL，文章内页图片正常显示。

**Comment by Licoy** [comment]
防盗链要允许空Referer头
