### ISSUE TITLE
网站界面重置

### ISSUE THREAD

**Issue by cddehsy** [Licoy/wordpress-theme-puock#279]
- 是否为已有功能：否
- 建议阐述：
首次打开主题，希望有一些默认配置，目前打开都是白板，全是空的
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/42635049/224468908-00faa11c-cf94-47bd-9ffc-90ccca80b434.png">

**Comment by Licoy** [comment]
你这网站内容都没有，再加任何配置都是无济于事。
