### ISSUE TITLE
缩略图自适应，不会裁剪

### ISSUE THREAD

**Issue by cddehsy** [Licoy/wordpress-theme-puock#280]
- 是否为已有功能：否
- 建议阐述：
后台已经添加禁止裁剪代码，wp后台也改了缩略图显示的大小，目前添加缩略图之后还是会裁剪
<img width="669" alt="image" src="https://user-images.githubusercontent.com/42635049/224468956-ec2453c6-ae51-424d-a411-9e33f4626638.png">

**Comment by Licoy** [comment]
缩略图肯定会进行裁剪，不然尺寸不匹配
