### ISSUE TITLE
代码块大于号会被渲染成 `&gt`

### ISSUE THREAD

**Issue by wt12318** [Licoy/wordpress-theme-puock#283]
您好，我的主题中如果使用代码块，一部分大于号会被渲染成 `&gt`:

https://wutaoblog.com.cn/index.php/2021/01/23/dplyr%e5%88%97%e5%bc%8f%e6%93%8d%e4%bd%9c/

但是在编辑器中显示正常：

![image](https://user-images.githubusercontent.com/39486023/224716501-cec7a9d7-0e00-4da0-b0ab-b631dfa75f79.png)

请问这个问题该如何解决？

谢谢

**Comment by Licoy** [comment]
这是个编辑器的问题吧

**Comment by wt12318** [comment]
但是编辑器中显示是正常的

**Comment by Licoy** [comment]
编辑器显示正常没有用

**Comment by wt12318** [comment]
那这个问题应该怎么解决呢

**Comment by Licoy** [comment]
你的编辑器用的什么

**Comment by wt12318** [comment]
用的这个
![image](https://user-images.githubusercontent.com/39486023/225035066-9e72a4b8-44fd-4a6a-aeee-8a43b36a291a.png)

**Comment by Licoy** [comment]
代码块里面的`<`，`>`等是会被转义的
