### ISSUE TITLE
请问能修改默认的文章缩略图吗。

### ISSUE THREAD

**Issue by Plainct** [Licoy/wordpress-theme-puock#286]
设置页面里面没找到相关的设置，是不是只能自己手动替换图片。

**Comment by Licoy** [comment]
缩略图的顺序是：文章第一张图->特色图片->随机图片

**Comment by Plainct** [comment]
其实我想问的是[随机图片]能不能替换…不过看样子，常规方法应该是不行了吧

**Comment by hyy34** [comment]
> 缩略图的顺序是：文章第一张图->特色图片->随机图片

请问特色图片如何加？并且在文章内不显示的那种。
