### ISSUE TITLE
建议添加文章目录以及开启 XML-RPC 服务

### ISSUE THREAD

**Issue by Ryanjiena** [Licoy/wordpress-theme-puock#29]
1. 文章目录对于长篇幅的文章非常有必要，可以帮助访客快速了解文章的内容结构。建议在文章页面右侧将 公告以及文章搜索 换成文章目录，或者添加按钮切换到文章目录。如图所示。

<table>
    <tr> 
        <td><img src="https://i.loli.net/2020/12/20/dUIum5RLErFH9iZ.jpg" border=0 /></td> 
        <td><img src="https://i.loli.net/2020/12/20/yRFlpNEnDVrXwIG.jpg" border=0 /></td> 
	</tr>
</table> 
2. 因为大多数人都会使用 markdown 进行写作，然后使用 XML-RPC 服务远程快速发布文章到 wordpress。所以建议开启 XML-RPC 服务 或者告知用户开启 XML-RPC 服务的方法，让用户自行决定。

**Comment by Licoy** [comment]
@Ryanjiena 文章目录目前正在计划开发中
@Ryanjiena 关于XML-RPC其实我还没有用过，所以需要先研究一下

**Comment by Ryanjiena** [comment]
第2个问题，把这一行注释了就行
https://github.com/Licoy/wordpress-theme-puock/blob/b301dbf729d837c7111d35b5d19764ec2024552d/inc/init.php#L18

**Comment by Ryanjiena** [comment]
第2个问题，想要开启 XML-RPC 服务的把这一行注释了就行。

https://github.com/Licoy/wordpress-theme-puock/blob/b301dbf729d837c7111d35b5d19764ec2024552d/inc/init.php#L18
