### ISSUE TITLE
最新版本2.7.6开启了chatgpt但首页没显示

### ISSUE THREAD

**Issue by codeonhub** [Licoy/wordpress-theme-puock#292]
- 主题版本号：
- WordPress版本：6.1.1
- PHP版本：8.1
- 问题阐述：
最新版本2.7.6开启了chatgpt但首页没显示
![image](https://user-images.githubusercontent.com/16483525/228423622-f3af171e-f337-43cc-a775-8e44e66d318d.png)

**Comment by Licoy** [comment]
页面-选择页面模板，不会在首页显示
