### ISSUE TITLE
希望主题能集成【微信公众号涨粉】短代码

### ISSUE THREAD

**Issue by jiffish** [Licoy/wordpress-theme-puock#293]
- 是否为已有功能：否
- 建议阐述：之前的【微信公众号涨粉】插件很久不更新了，编辑器已经更新没发用了。  自己修改代码的话，主题更新就又得改一遍。子主题更是动了牛刀。。。
建议顺手集成了吧，和主题自带的【输入密码可见】就差css代码美化和加入公众号二维码图片链接了。 

例如：https://zhuanlan.zhihu.com/p/109090057
https://pic3.zhimg.com/80/v2-6a4858d182d9e2f7dcfc75d7a9e04602_720w.webp

加油！

**Comment by Licoy** [comment]
此功能不会被支持
