### ISSUE TITLE
可以考虑更加美观的灯箱吗

### ISSUE THREAD

**Issue by lz732895965** [Licoy/wordpress-theme-puock#294]
- 是否为已有功能：是
- 建议阐述：可以考虑更加美观的灯箱吗？因为主题默认的灯箱在移动端的优化确实有点差，我试着用其他灯箱，但是会和主题有冲突，感觉有点不兼容，试着修改代码但是主题一升级就又会覆盖掉，所以建议优化一下主题默认的灯箱。

**Comment by Licoy** [comment]
那你有推荐的灯箱组件吗？要适合开源使用，最好完全是MIT/GPL协议

**Comment by lz732895965** [comment]
这个我还真没想过，抱歉啊。我以前用的是fancybox，感觉也还不错。
