### ISSUE TITLE
文章内图片无法生成缩略图

### ISSUE THREAD

**Issue by yinhedot** [Licoy/wordpress-theme-puock#295]
- 主题版本号：2.7.6
- WordPress版本：6.2
- PHP版本：[选填]
- 问题阐述：

图片目录： /uploads, 直接通过ftp上传

测试页面： https://yinhe.co/

错误提示：
A TimThumb error has occured
The following error(s) occured:
Could not find the internal image you specified.

Query String : w=280&h=160&a=c&zc=1&q=90&src=/uploads/20230409_md2wp%E8%84%9A%E6%9C%AC_%E5%9B%BE%E7%89%87%E6%B5%8B%E8%AF%95.jpg
TimThumb version : 2.8.14

![image](https://user-images.githubusercontent.com/79557759/230755830-68f7384a-3069-40ee-a65b-3c6cb8eebb32.png)

![image](https://user-images.githubusercontent.com/79557759/230755816-3836e990-f87d-4a1a-b7d5-9cfb6bcea197.png)

**Comment by yinhedot** [comment]
已通过随机头图的方式解决
1.上传相关图片到对应目录

2.在主题设置的底部统计代码添加如下代码

`<script>
	window.onload = function() {

		function shuffle(arr) {
			var l = arr.length
			var index, temp
			while (l > 0) {
				index = Math.floor(Math.random() * l) temp = arr[l - 1] arr[l - 1] = arr[index] arr[index] = temp l--
			}
			return arr
		}

		$thumbnail_pics_list = ["/uploads/20230409_puock_01.jpg", "/uploads/20230409_puock_02.jpg", "/uploads/20230409_puock_03.jpg", "/uploads/20230409_puock_04.jpg", "/uploads/20230409_puock_05.jpg", "/uploads/20230409_puock_06.jpg", "/uploads/20230409_puock_07.jpg", "/uploads/20230409_puock_08.jpg", "/uploads/20230409_puock_09.jpg", "/uploads/20230409_puock_10.jpg", "/uploads/20230409_puock_11.jpg", "/uploads/20230409_puock_12.jpg", "/uploads/20230409_puock_13.jpg", "/uploads/20230409_puock_14.jpg", "/uploads/20230409_puock_15.jpg", "/uploads/20230409_puock_16.jpg", "/uploads/20230409_puock_17.jpg", "/uploads/20230409_puock_18.jpg", "/uploads/20230409_puock_19.jpg", "/uploads/20230409_puock_20.jpg"];

		shuffle($thumbnail_pics_list);
		var i = 0;
		$(".thumbnail img").each(function() {
			$(this).attr("src", $thumbnail_pics_list[i]);
			i += 1;
		});

	}
</script>`

**Comment by Licoy** [comment]
图片路径不要带中文

**Comment by yinhedot** [comment]
> 图片路径不要带中文

避免不了中文，换了方案
