### ISSUE TITLE
主题模式：日光和暗黑前台问题

### ISSUE THREAD

**Issue by hetmly** [Licoy/wordpress-theme-puock#299]
- 主题版本号：
- WordPress版本：6.2
- PHP版本：7.4
- 问题阐述：

1、先开启了前台暗黑模式+可切换主题日光和暗黑
2、用户选了日光模式
3、然后我在后台关闭可切换主题模式+前台暗黑模式

问题：用户无法自动变成暗黑模式，在点击网站页面会闪一下黑色，然后变回日光模式

**Comment by Licoy** [comment]
首先确认你有没有开启CDN缓存？

**Comment by hetmly** [comment]
> 首先确认你有没有开启CDN缓存？

开启了，那我应该排除缓存哪个文件或者文件夹才不会出现这个问题呢？

**Comment by Licoy** [comment]
缓存了任何页面都没用，因为缓存了后页面颜色模式都是通过js来处理的，所以会闪
