### ISSUE TITLE
跨站脚本攻击

### ISSUE THREAD

**Issue by jacksunhack** [Licoy/wordpress-theme-puock#301]
- 主题版本号：
- WordPress版本：6.2
- PHP版本：7.4
- 问题阐述：
aapanel 已经开启防跨站攻击
在chatgpt那个页面输入一段代码 目前测试css发送给chatgpt的时候就会执行。
![195E407B1EBBAF887DC152A6C2548B49](https://user-images.githubusercontent.com/47632644/233623095-2573cb84-6fd9-4ee8-a908-ddc1dd8aadde.jpg)

**Comment by Licoy** [comment]
那个记录只会使用者自己看得到，其他用户不会受到任何影响，这就相当于你打开了开发者工具为所欲为，但是一刷新就什么都没有了～
