### ISSUE TITLE
求大佬加一个可以使用文章第一张图片当作预览图

### ISSUE THREAD

**Issue by Adoubf** [Licoy/wordpress-theme-puock#308]
- 是否为已有功能：否
- 建议阐述：
-   默认情况下文章未设置特色图片就使用文章的第一张图片当作特色图片
-   优点：省时省空间

**Comment by Licoy** [comment]
此功能已存在：特色图片->文章内第一张图->随机图

**Comment by Adoubf** [comment]
十分感谢！！

发件人: 憧憬Licoy ***@***.***>
发送时间: 2023年5月7日 16:47
收件人: Licoy/wordpress-theme-puock ***@***.***>
抄送: Mankanov Alleman ***@***.***>; Author ***@***.***>
主题: Re: [Licoy/wordpress-theme-puock] 求大佬加一个可以使用文章第一张图片当作预览图 (Issue #308)


此功能已存在：特色图片->文章内第一张图->随机图
