### ISSUE TITLE
添加广告代码后保存配置代码丢失！

### ISSUE THREAD

**Issue by aeego** [Licoy/wordpress-theme-puock#31]
添加的是百度的广告代码，具体看图！
![1](https://user-images.githubusercontent.com/76577806/103119154-1d4ffd00-46ad-11eb-8248-13aa322634ad.jpg)
![2](https://user-images.githubusercontent.com/76577806/103119170-348eea80-46ad-11eb-9d00-31427cd17ebb.jpg)

**Comment by Licoy** [comment]
@aeego 谢谢反馈，问题原因已找到，可自行先将`inc/setting/options.php`中的`'type' => 'textarea'`替换为
```
'type' => 'editor',
'settings' => $editorSettings
```
进行解决

**Comment by Licoy** [comment]
具体修改代码可以参见：https://github.com/Licoy/wordpress-theme-puock/commit/2430e453255a862f512136c292058ab7ef2f87d7

**Comment by Licoy** [comment]
已修复 close.
