### ISSUE TITLE
文章页面如果插入了代码，此文章页面的将HTML压缩成一行就会失效，其他页面正常。

### ISSUE THREAD

**Issue by lemon360** [Licoy/wordpress-theme-puock#312]
- 主题版本号：2.7.9
- WordPress版本：6.2.2
- PHP版本：[8.0]
- 问题阐述：文章页面如果插入了代码，此文章页面的将HTML压缩成一行就会失效，其他页面正常。还可能会造成文章页面侧边栏错位。

**Comment by Licoy** [comment]
关闭主题设置-压缩HTML
