### ISSUE TITLE
[Bug]在自定义页添加搜索小工具最终没有显示标题

### ISSUE THREAD

**Issue by jd82k** [Licoy/wordpress-theme-puock#316]
- 主题版本号：2.7.9
- WordPress版本：6.2
- PHP版本：[选填]
- 问题阐述：puock在WordPress后台外观->自定义页面添加小工具时，假设在首页-侧边栏添加一个puock搜索小工具，如果不进行标题修改，只用默认标题，最终实际显示页面会出现无标题的bug。
此问题只会在使用外观->自定义页面时出现，使用外观->小工具页面操作不会出现。
问题初步分析应该为WordPress在外观->自定义页面处，如果不编辑<input>框不会触发保存请求，所以在使用默认标题或者默认搜索提示词的情况下（不编辑input的value），不会触发ajax请求。

**Comment by Licoy** [comment]
实测是现实的呀，没有问题
