### ISSUE TITLE
用外链媒体做特色图的文章不会显示封面

### ISSUE THREAD

**Issue by AniBullet** [Licoy/wordpress-theme-puock#319]
- 主题版本号：2.7.10
- WordPress版本：6.2.2
- PHP版本：[选填]
- 问题阐述：用了 External Media without Import 插件能填外链存图片到媒体库，但是这种图片首页无法显示封面。另外封面能支持gif么~

**Comment by Licoy** [comment]
重复问题，查看缩略图白名单
