### ISSUE TITLE
主题可以使用 wp statics 统计吗？

### ISSUE THREAD

**Issue by AniBullet** [Licoy/wordpress-theme-puock#320]
看 f12 一直有一个报错  `/wp-json/wp-statistics/v2/hit?wp_statistics_hit_rest=yes&track_all=1&current_page_type=home&current_page_id=0&search_query&page_uri=Lw=&referred=https%3A%2F%2Fwww.xxxxxxx.com%2F&_=xxxxxxxxxxx `

**Comment by Licoy** [comment]
无测试，不支持
