### ISSUE TITLE
f12 有一个 theia-sticy-sidebar 的 warning

### ISSUE THREAD

**Issue by AniBullet** [Licoy/wordpress-theme-puock#321]
- 主题版本号：2.7.10
- WordPress版本：6.2.2
- PHP版本：[选填]
- 问题阐述：`DevTools failed to load source map: Could not load content for https://www.anibullet.com/wp-content/themes/wordpress-theme-puock-2.7.10/assets/dist/js/maps/theia-sticky-sidebar.min.js.map: Unexpected token '<', "<!doctype "... is not valid JSON`

**Comment by Licoy** [comment]
这个可以忽略
