### ISSUE TITLE
建议增加目录侧边栏

### ISSUE THREAD

**Issue by Codefor4learn** [Licoy/wordpress-theme-puock#322]
- 是否为已有功能：是
- 建议阐述：

建议增加一个目录小工具，并且可以选择是否不跟随屏幕移动，比如这篇文章的目录小工具：https://www.rsecc.cn/868.html

**Comment by Codefor4learn** [comment]
并非已有功能吧，目录放在侧边栏会更方便一点，不然需要多点击才能看见

**Comment by wkingnet** [comment]
或者说将目录添加到小工具中，然后就可以实现把目录插入到侧边栏。最好还可以实现目录随页面滚动而滚动
