### ISSUE TITLE
评论提交后的跳转存在异常

### ISSUE THREAD

**Issue by acctZCW** [Licoy/wordpress-theme-puock#325]
- 主题版本号：2.7.10
- WordPress版本：6.2.2
- PHP版本：8.2
- 问题阐述：评论提交后没有正常跳转回原界面，而是跳转到了新的admin-ajax.php界面，但是评论的提交是完成了的。

![image](https://github.com/Licoy/wordpress-theme-puock/assets/40493551/2962bc96-3c29-40e4-a909-37a0f4729914)

**Comment by Licoy** [comment]
f12看控制台，你应该是有什么插件或配置影响了主题的js执行

**Comment by acctZCW** [comment]
> f12看控制台，你应该是有什么插件或配置影响了主题的js执行

提交后控制台没有任何输出内容。

我切换其他主题提交评论是正常跳转的，是否能定位到具体的执行代码？

**Comment by Licoy** [comment]
你这个100%都是js被影响加载执行了

**Comment by acctZCW** [comment]
留一个解决方案在这吧。

怀疑是静态资源的加载出现了问题，可以考虑在主题中配置静态资源从CDN进行加载而非本地，同时WP Githuber也使用CDN加载，这样就没问题了。
