### ISSUE TITLE
博主，请问ChatGPT问答之头像不显示?

### ISSUE THREAD

**Issue by abcpure1234567** [Licoy/wordpress-theme-puock#326]
博主，请问ChatGPT问答之头像不显示?
https://licoy.cn/3590.html/comment-page-3/#comments
https://upload.cc/i1/2023/07/20/xX0pP8.jpg
https://mjj.today/i/WG2XBd

憧憬Licoy 博主
2023-07-21 19:46:14  回复
f12查看一下头像链接

PURE 评论达人 LV.1
2023-07-22 15:47:40  回复
img src=”” class=”avatar md-avatar” alt=”avatar”

憧憬Licoy 博主
2023-07-24 13:57:01  回复
好的，github提个issue吧，之后看看

**Comment by abcpure1234567** [comment]
![image](https://github.com/Licoy/wordpress-theme-puock/assets/38415081/5ffc7483-d877-409c-b19d-3db337140e51)
![image](https://github.com/Licoy/wordpress-theme-puock/assets/38415081/32518ced-dae8-49f5-944b-3101d7d379df)

**Comment by Licoy** [comment]
实测没有问题

**Comment by Licoy** [comment]
![image](https://github.com/Licoy/wordpress-theme-puock/assets/20410697/45bafb63-42c5-4923-ae34-8fbac4de7276)
