### ISSUE TITLE
主题删除失败

### ISSUE THREAD

**Issue by playNoA** [Licoy/wordpress-theme-puock#327]
- 主题版本号：2.7.10
- WordPress版本：6.2.2
- PHP版本：7.4.3-4ubuntu2.19 （支持64位数值）
- 问题阐述：删除主题时，提示“删除失败：请求的主题不存在。”

**Comment by Licoy** [comment]
那就是主题不存在呀，可能已经被删除了或者目录对不上

**Comment by playNoA** [comment]
在主题页面点击删除的时候提示提示的。
