### ISSUE TITLE
访问首页会增加文章的阅读量

### ISSUE THREAD

**Issue by hausen1012** [Licoy/wordpress-theme-puock#334]
- 主题版本号：最新
- WordPress版本：6.0.3
- PHP版本：[选填]
- 问题阐述：
访问首页会增加文章的阅读量，有时候加1有时候加2.

**Comment by Licoy** [comment]
1. 是否开启CDN
2. 是否开启了异步增加浏览量的开关

**Comment by hausen1012** [comment]
都开了

**Comment by Licoy** [comment]
那就是正常的，有时候CDN会回源+1次，然后异步又会+1次

**Comment by hausen1012** [comment]
这个解决的方式是？

**Comment by Licoy** [comment]
这是正常的，如果你的页面开启了缓存那么就需要异步计数，反之就不需要开启
