### ISSUE TITLE
License版本问题

### ISSUE THREAD

**Issue by skyhhjmk** [Licoy/wordpress-theme-puock#337]
# 应该遵守GNU GPL v2还是v3

## 仓库中有声明
`This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License as 
published by the Free Software Foundation; either version 2 of 
the License, or (at your option) any later version.`

## 但在最新的License文件中
`GNU GENERAL PUBLIC LICENSE
                       Version 3, 29 June 2007`
虽然开头为version 3，但分析内容后表明这是version 2版本

## 同时，GitHub也提到了
`Licoy/wordpress-theme-puock is licensed under the
GNU General Public License v3.0`

**Comment by Licoy** [comment]
V3

![image](https://github.com/Licoy/wordpress-theme-puock/assets/20410697/63917738-ac83-4997-8aeb-fb73407af5cf)
