### ISSUE TITLE
timthumb疑似不兼容

### ISSUE THREAD

**Issue by 1754259520** [Licoy/wordpress-theme-puock#341]
- 主题版本号：
- WordPress版本：6.3.1
- PHP版本：[选填]7.4
- 问题阐述：
timthumb在图片名后加入?v=导致无法正确找到图片，去除后可以正常裁剪访问
(https://www.vpspc.org/wp-content/themes/wordpress-theme-puock-2.8.0/timthumb.php?w=280&h=160&a=c&zc=1&q=90&src=https://www.vpspc.org/wp-content/uploads/2023/09/123-1024x478.png?v=1695892869)
![image](https://github.com/Licoy/wordpress-theme-puock/assets/56875288/abed73ad-0630-425b-a3e1-8055654c816e)
![image](https://github.com/Licoy/wordpress-theme-puock/assets/56875288/6e18208e-0b88-4ffc-9372-6505d2747826)

**Comment by Licoy** [comment]
<img width="760" alt="image" src="https://github.com/Licoy/wordpress-theme-puock/assets/20410697/cf1f1bff-2927-476d-ae79-87fc2d2a90df">

query参数部分重复了，这是不合法的URL

**Comment by 1754259520** [comment]
我怀疑可能是wp6.3.1导致的这个问题，稍后我会进行确认

**Comment by 1754259520** [comment]
经过确认，6.0全新安装的并没有出现这个问题，而直接安装wp6.3.1的存在这个问题，
