### ISSUE TITLE
如何才能直接编写文章的时候粘贴图片，而不是上传。

### ISSUE THREAD

**Issue by JarvanDing** [Licoy/wordpress-theme-puock#344]
一直用着官方编辑器，我是边写边粘贴图片说明，文章完成的很快，这个编辑器都是要先上传再来找图片，好麻烦！请问如何改回官方默认编辑器呢？

**Comment by Licoy** [comment]
主题不提供任何编辑器，你依然可以用官方的编辑器进行撰写文章
