### ISSUE TITLE
ChatGPT不能连续对话

### ISSUE THREAD

**Issue by sanxianla** [Licoy/wordpress-theme-puock#351]
- 主题版本号：2.80
- WordPress版本：6.41
- PHP版本：7.4.33
- 问题阐述：在主题添加OpenAI官方api之后尝试使用ChatGPT发现不能连续对话且每次问答速度很慢
附图https://picdl.sunbangyan.cn/2023/11/18/6272ed69b2cb8569857c8d3aa63e265d.jpg

**Comment by happykl-cn** [comment]
这个可以玩玩吧。上下文角色扮演什么都不支持。有需求建议还是官方或者镜像。

**Comment by sanxianla** [comment]
感觉这个界面还挺简洁的，要是能满足基础上下文对话功能就够了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月30日(周四) 晚上8:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Licoy/wordpress-theme-puock] ChatGPT不能连续对话 (Issue #351)




 
这个可以玩玩吧。上下文角色扮演什么都不支持。有需求建议还是官方或者镜像。

**Comment by Licoy** [comment]
如果要更好一点的可以转至：https://github.com/Licoy/ChatGPT-Midjourney，本身主题内集成这个只是提供一个基础的
