### ISSUE TITLE
文章编辑页的首页幻灯片url 不可用

### ISSUE THREAD

**Issue by LiYeLin** [Licoy/wordpress-theme-puock#36]
![image](https://user-images.githubusercontent.com/29306500/103518443-bac9de80-4eae-11eb-8279-72c91e0bb33d.png) 

![image](https://user-images.githubusercontent.com/29306500/103518466-c61d0a00-4eae-11eb-883a-14f4de59d8a3.png) 

如图所示 图片地址 ：https://i.loli.net/2020/11/18/3DyzOHVCIoE1ATR.png

**Comment by Licoy** [comment]
因为使用的外部图片地址，在`timthumb.php`中添加地址白名单即可，具体位置：
https://github.com/Licoy/wordpress-theme-puock/blob/cb715469b69ea09474cc7cdfe300aa7d66fb5acd/timthumb.php#L133

**Comment by LiYeLin** [comment]
@Licoy 
![image](https://user-images.githubusercontent.com/29306500/103602499-25c6f400-4f47-11eb-94af-f490ac2e26e0.png)

把图床的根域名配上也不行啊，完整路径配置上也不行  不太懂php，是我加入白名单的方式有问题吗

**Comment by Licoy** [comment]
不用加协议，去掉http[s]://
