### ISSUE TITLE
使用阿里云的oss+cdn的图片内容，不能自动提取缩略图，加缩略图白名单也不行

### ISSUE THREAD

**Issue by ytg3114** [Licoy/wordpress-theme-puock#362]
- 主题版本号：2.80
- WordPress版本：6.2
- PHP版本：[选填]
- 问题阐述：使用阿里云的oss+cdn的图片内容，不能自动提取缩略图，加缩略图白名单也不行

**Comment by Licoy** [comment]
你可以自行访问缩略图URL看看页面提示什么

**Comment by ytg3114** [comment]
A TimThumb error has occured
The following error(s) occured:
An error occured fetching image.

**Comment by ytg3114** [comment]
A TimThumb error has occured
The following error(s) occured:
An error occured fetching image.

**Comment by ytg3114** [comment]
用的是bb.cc/wp-content/themes/wordpress-theme-puock-master/timthumb.php?w=280&h=160&a=c&zc=1&q=90&src=https://xx.cc/BAjcglimg/i/2023/12/8624347616393857682.png

**Comment by Licoy** [comment]
可能是设置了防盗链不允许空头访问，诸如此类，导致图片拉取失败
