### ISSUE TITLE
按钮时长过短

### ISSUE THREAD

**Issue by zycwer** [Licoy/wordpress-theme-puock#363]
- 主题版本号：2.8.0
- WordPress版本：6.4.2
- PHP版本：8.2
- 问题阐述：在我按下分享按钮和评论的表情按钮时，闪烁了一下选项，有时按下去，就消失了

https://github.com/Licoy/wordpress-theme-puock/assets/117061348/22b2616f-6ba4-4d59-bf40-5bdec4a7e589

**Comment by Licoy** [comment]
你应该是有什么插件或者其他的东西影响到了
