### ISSUE TITLE
bootstrapcdn 怎么改成本地的

### ISSUE THREAD

**Issue by fallsea** [Licoy/wordpress-theme-puock#366]
https://[maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css?ver=4.4.0](https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css?ver=4.4.0)

目前这个是在线的应用，导致很慢，想使用本地的，怎么修改

**Comment by Licoy** [comment]
这个是你自己插件或者其他组件产生的东西，主题不含有此资源引用
