### ISSUE TITLE
GrAvatar加载源 切换无效。

### ISSUE THREAD

**Issue by Eveaz** [Licoy/wordpress-theme-puock#37]
今天博客中的头像全部加载不出来，我才知道一直以来博客都是加载的 secure.gravatar.com 官方源的头像。
但是我在主题设置里面一直设置的是官方CN的SSL源。

在主题设置里面切换 CN、loli、v2ex都无效。

点进大佬的博客也发现全部加载的是 secure.gravatar.com的头像。
![image](https://user-images.githubusercontent.com/51356521/103523820-7131c180-4eb7-11eb-8b2d-4a242cca70aa.png)

希望大佬能够修复。

**Comment by Eveaz** [comment]
自己更新解决办法：
在主题文件夹 inc/fun/opt.php 大概第97行。
原始代码
```
function v2ex_ssl_avatar($avatar) {
    global $gravatar_urls;
    return str_replace("http://","https://",str_replace( $gravatar_urls, 'cdn.v2ex.com', $avatar ));
}
```
修改如下：
```
function v2ex_ssl_avatar($avatar) {
    $avatar = str_replace(array("//gravatar.com/", "//secure.gravatar.com/", "//www.gravatar.com/", "//0.gravatar.com/", 
"//1.gravatar.com/", "//2.gravatar.com/", "//cn.gravatar.com/"), "//cdn.v2ex.com/", $avatar);
return $avatar;}

```
其它的CDN源也可以参考，只需要替换相关CDN的域名即可。
我个人推荐使用极客族公共加速服务的CDN，网址：https://cdn.geekzu.org/cached.html

**Comment by Licoy** [comment]
此问题已修复，是由于未添加`secure.gravatar.com`而导致安全站点无法更换，谢谢反馈。

**Comment by Licoy** [comment]
@Eveaz 此问题已解决，若仍有疑问请重新打开此issue并回复。
