### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by UEFI233** [Licoy/wordpress-theme-puock#371]
- 主题版本号：2.8.0
- WordPress版本：WordPress 6.4.2
- PHP版本：[7.2.33]
- 问题阐述：
在启用主题时，出现了如下错误：
`Parse error: syntax error, unexpected ')' in /www/wwwroot/WordPress/wp-content/themes/wordpress-theme-puock-2.8.0/inc/setting/PuockSetting.php on line 69`

**Comment by Licoy** [comment]
最低支持PHP版本：7.4
