### ISSUE TITLE
配置保存失败

### ISSUE THREAD

**Issue by UEFI233** [Licoy/wordpress-theme-puock#373]
- 主题版本号：2.8.0
- WordPress版本：6.4.2
- PHP版本：[7.4]
- 问题阐述：
- 在进行保存配置时，出现如下错误
- `配置保存失败: [object Object]`

**Comment by Licoy** [comment]
提供一下F12在console的错误，以及相关请求的network响应

**Comment by UEFI233** [comment]
在关闭CloudFlare CDN加速后，配置保存正常

**Comment by songyp0505** [comment]
> 提供一下F12在console的错误，以及相关请求的network响应

load-scripts.php?c=1&load%5Bchunk_0%5D=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=6.4.2:2 

Mixed Content: The page at 'https://xxxxx/wp-admin/admin.php?page=puock-options' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://xxxxx/wp-admin/admin-ajax.php?action=update_theme_options'. This request has been blocked; the content must be served over HTTPS.

**Comment by vbskycn** [comment]
防火墙拦截也会这样，

**Comment by Licoy** [comment]
重新保存一下固定链接，https网页下禁止请求http的api
