### ISSUE TITLE
Security contact

### ISSUE THREAD

**Issue by mal-tee** [Licoy/wordpress-theme-puock#376]
Hello maintainer(s), 

I am a security researcher from the Institute of Application Security at TU Braunschweig, Germany. We discovered a (potential) security vulnerability in your project.

We would like to report this vulnerability to you in a responsible and ethical manner.
Therefore, we do not want to disclose any details of the vulnerability publicly until you have had a chance to review and fix it.

**Could you please let us know your prefered way of receiving security reports?**

You can contact us at ias-disclosure@tu-braunschweig.de or by replying to this issue.

Thank you for your attention and cooperation.

**Comment by Licoy** [comment]
please send email to `licoycn@gmail.com`, thanks

**Comment by mal-tee** [comment]
Hi, 

I haven't received an email yet. Is there another way to contact you?

Best
