### ISSUE TITLE
老大可不可以做个如截图的下载页面窗口哈

### ISSUE THREAD

**Issue by syx594** [Licoy/wordpress-theme-puock#38]
老大可不可以做个如截图的下载页面窗口哈
<img src="https://i.loli.net/2021/01/04/ymMfkB8JvPebp6a.jpg" </>

**Comment by Licoy** [comment]
本主题更倾向于叙述性博客主体，所以暂无此计划，谢谢提议。

**Comment by Licoy** [comment]
@syx594 由于长时间未回复先暂时关闭此issue，若仍有疑问请重新打开此issue并回复
