### ISSUE TITLE
parse_user_agent变量冲突问题

### ISSUE THREAD

**Issue by tjsky** [Licoy/wordpress-theme-puock#380]
- 主题版本号：2.8.1
- WordPress版本：6.4.3
- PHP版本：8.1
- 问题阐述：
就是一个变量名`parse_user_agent`冲突的问题，
位于`\wordpress-theme-puock\inc\user-agent-parse.php` 26行。
有一个比较常见的SEO插件`Rank Math SEO`也声明了这个变量名。

**Comment by akige** [comment]
这个问题如何解决呢？最新版貌似还有这个问题

**Comment by tjsky** [comment]
> 这个问题如何解决呢？最新版貌似还有这个问题

你可自己改一下变量名
把[inc/user-agent-parse.php](https://github.com/Licoy/wordpress-theme-puock/blob/e6685697540d2f3f3e1efe285c7c11d75e2d0735/inc/user-agent-parse.php#L25)、[inc/fun/comment.php](https://github.com/Licoy/wordpress-theme-puock/blob/e6685697540d2f3f3e1efe285c7c11d75e2d0735/inc/fun/comment.php#L3)、[inc/fun/comment-ajax.php](https://github.com/Licoy/wordpress-theme-puock/blob/e6685697540d2f3f3e1efe285c7c11d75e2d0735/inc/fun/comment-ajax.php#L3)

里的`parse_user_agent`统一给改成别的名字，比如`puock_parse_user_agent`
