### ISSUE TITLE
QQ登录提示  QQ互联加强网站应用回调地址校验

### ISSUE THREAD

**Issue by xiaoyi510** [Licoy/wordpress-theme-puock#382]
- 主题版本号：2.8.1
- WordPress版本：6.4.3
- 问题阐述：
redirect uri is illegal(100010)

[通知: QQ互联加强网站应用回调地址校验]

其中QQ应用中已设置回调地址为
https://xxxxxx.com/wp-admin/admin-ajax.php
QQ应用已经是审核通过了的

![image](https://github.com/Licoy/wordpress-theme-puock/assets/20254874/113d9a68-43b3-493d-8192-79765ef799da)

**Comment by Licoy** [comment]
自己的问题，回调地址错误
