### ISSUE TITLE
文章特色图片显示异常

### ISSUE THREAD

**Issue by Openfan-Alex** [Licoy/wordpress-theme-puock#387]
- 主题版本号：最新
- WordPress版本：最新
- PHP版本：7.4
- 问题阐述：切换puock主题后文章的特色图片无法在博客主页正常显示，图片地址有误，切换其他主题就正常，我不知道是puock主题哪里出现问题导致这个错误，希望作者大大快点看到并帮忙解决

**Comment by Lvshujun0918** [comment]
贴一下f12网络面板显示的错误（或者控制台也行）

**Comment by hxysaury** [comment]
这个问题怎么解决？打开控制面板显示图片400

**Comment by Lvshujun0918** [comment]
请检查你图片的域名是否和站点相同，不是的话请加入白名单

**Comment by hxysaury** [comment]
我用的阿里云oss，已经加入缩略图白名单了，其他主题都可以，这个主题却不可以显示

**Comment by Lvshujun0918** [comment]
能否给个站点地址，我看一下
另外是否满足了白名单下面的提示：“若使用了其他外链图片须在此处添加外链域名以允许：一行一个，不要带 http:// 或 https:// 协议头，例如：blog.example.com”

**Comment by hxysaury** [comment]
https://www.saury.site/

**Comment by Lvshujun0918** [comment]
白名单的配置应该为：“img-blog.csdnimg.cn”，是否正确？如果正确，尝试清空下缓存

**Comment by hxysaury** [comment]
设置没问题

**Comment by Lvshujun0918** [comment]
检查一下OSS有没有使用防盗链，另外烦请截图一下白名单的配置

**Comment by hxysaury** [comment]
![Uploading Snipaste_2024-05-17_14-08-15.png…]()

**Comment by hxysaury** [comment]
![Snipaste_2024-05-17_14-08-15](https://github.com/Licoy/wordpress-theme-puock/assets/67418885/e0465685-9c2c-426c-a57e-329a88a0efd6)

**Comment by hxysaury** [comment]
文章里的图片都可以显示，就是首页跟侧边栏的不显示

**Comment by Lvshujun0918** [comment]
> 文章里的图片都可以显示，就是首页跟侧边栏的不显示

你的阿里OOS配置有问题，用链接访问图片直接下载了。例：https://saury-img.oss-cn-beijing.aliyuncs.com/imgs/350d985b39cc0c834331f0cd687847f4.png

按百度上的说法，是把阿里OSS中的图片的“类型”从[image/jpeg]改成[image/jpg]

**Comment by alexxin139** [comment]
> 请检查你图片的域名是否和站点相同，不是的话请加入白名单

域名相同啊

**Comment by hxysaury** [comment]
OSS域名自定义了，现在有了好转，图片不报400错误了，但是就是不显示图片

**Comment by Lvshujun0918** [comment]
> 还有就是我发现直接在 主题那么设置缩略图不起作用，我直接vim timthumb.php 修改$ALLOWED_SITES = []才有作用

怀疑文件权限问题，我这边测试是正常的，你应该把主题文件夹和其中的文件配置成运行php（或nginx）的用户所有

**Comment by hxysaury** [comment]
主题文件改成www用户了，还是不显示图片

**Comment by Lvshujun0918** [comment]
> 主题文件改成www用户了，还是不显示图片

我看主页上thumb.php负责的裁剪的图片已经正常显示了，内页你自定义的OSS域名上配置的SSL证书有问题
