### ISSUE TITLE
发表和以前相同的评论会提示已经发表过

### ISSUE THREAD

**Issue by hausen1012** [Licoy/wordpress-theme-puock#389]
应该判断一下时间，一两分钟以内的才提示，否则这样限制永远不能发表一样的评论。比如说有人友联，一般都是回已添加，现在必须加点符号才行，每次还要不一样

**Comment by Lvshujun0918** [comment]
在`/wordpress-theme-puock-2.8.1/inc/fun/comment-ajax.php`的126行附近实现了查找重复评论的功能，你可以自行修改sql语句来实现，或者直接注释掉去除这个功能

**Comment by hausen1012** [comment]
感谢，不过还是希望作者能够修复，这个算是bug来的

**Comment by Licoy** [comment]
非BUG，主要就是为了防止重复提交重复信息

**Comment by hausen1012** [comment]
> 非BUG，主要就是为了防止重复提交重复信息

别人提交友链，自己都不能回复同一句好的，希望可以解除管理员的限制

**Comment by Licoy** [comment]
> > 非BUG，主要就是为了防止重复提交重复信息
> 
> 别人提交友链，自己都不能回复同一句好的，希望可以解除管理员的限制

若有需要，管理员可以在后台进行回复，此处不受限制
