### ISSUE TITLE
如何关闭主题代码高亮功能？

### ISSUE THREAD

**Issue by Arisono** [Licoy/wordpress-theme-puock#39]
如何关闭主题代码高亮功能？

**Comment by Licoy** [comment]
目前暂无法进行关闭，可以自行到pages.js中进行关闭:

https://github.com/Licoy/wordpress-theme-puock/blob/cb715469b69ea09474cc7cdfe300aa7d66fb5acd/assets/js/pages.js#L86

**Comment by Licoy** [comment]
@Arisono 此问题已回执但长时间未得到回复先暂时关闭，若仍有疑问请重新打开此issue并回复。
