### ISSUE TITLE
文章点赞异常(POST admin-ajax.php返回404)

### ISSUE THREAD

**Issue by ics-pedia** [Licoy/wordpress-theme-puock#390]
在文章内点赞，页面反馈“点赞异常”;
F12抓包发现错误，POST返回404，请问下怎么解决呢？
Restquest请求信息
Request URL:http://8.134.206.130/wp-admin/admin-ajax.php
Request Method:POST
Status Code:404 Not Found
Remote Address:8.134.206.130:80
Referrer Policy:strict-origin-when-cross-origin

action=puock_like&um_id=1&um_action=like

**Comment by Lvshujun0918** [comment]
![image](https://github.com/Licoy/wordpress-theme-puock/assets/41245552/54001ba4-fab8-43b0-a7dc-5bff2565378b)
![image](https://github.com/Licoy/wordpress-theme-puock/assets/41245552/4fc0154f-fc46-4cc9-aaa4-a570e62149fb)
我这里似乎没有问题，你可能要提供更多信息

**Comment by ics-pedia** [comment]
尝试了多遍重装系统，依然无法解决问题，不知道是不是版本问题
系统： ubuntu 22.04
php版本：PHP Version 8.1.2-1ubuntu2.14
wordpress版本: 6.4.3
apache2版本： Apache/2.4.52 (Ubuntu)

**Comment by ics-pedia** [comment]
问题接除，是由于访问网站根目录和伪静态的问题；

**Comment by 522089669** [comment]
可以帮我看看吗，我的也是点赞有问题

**Comment by Lvshujun0918** [comment]
请新开一个issue，截屏你的日志和控制台错误

**Comment by 522089669** [comment]
> 请新开一个issue，截屏你的日志和控制台错误

新开了
