### ISSUE TITLE
[bug] 媒体:图片名称中存在中文,插入文章后,无法加载404

### ISSUE THREAD

**Issue by Djooxx** [Licoy/wordpress-theme-puock#391]
- 主题版本号：2.8.1
- WordPress版本：6.4.3
- PHP版本：[选填]
- 问题阐述：
[bug] 媒体:图片名称中存在中文,插入文章后,无法加载,404
对404的图片url进行decode结果也是正确的
/wp-content/uploads/2024/03/name%20%E5%90%8D%E5%AD%97.png
![image](https://github.com/Licoy/wordpress-theme-puock/assets/26398488/35d5a9ec-c027-47c3-a9ca-0a57e6c5e9fc)
切换到其他主题可以正常加载图片.

**Comment by Djooxx** [comment]
自测参考:
图片名称:
终结者2：审判日.Terminator.2.Judgment.Day_.1991-poster.jpg
name-副本.png
name副本.png

Puock主题加载的图片url:(404)
https://host/wp-content/uploads/2024/03/%20%E7%BB%88%E7%BB%93%E8%80%85%202%EF%BC%9A%E5%AE%A1%E5%88%A4%E6%97%A5.Terminator.2.Judgment.Day_.1991-poster.jpg
https://host/wp-content/uploads/2024/03/name-%20%E5%89%AF%E6%9C%AC.png
https://host/wp-content/uploads/2024/03/name%20%E5%89%AF%E6%9C%AC.png

Blogier主题加载的图片url:(正常加载)
https://host/wp-content/uploads/2024/03/%E7%BB%88%E7%BB%93%E8%80%852%EF%BC%9A%E5%AE%A1%E5%88%A4%E6%97%A5.Terminator.2.Judgment.Day_.1991-poster.jpg
https://host/wp-content/uploads/2024/03/name-%E5%89%AF%E6%9C%AC.png
https://host/wp-content/uploads/2024/03/name%E5%89%AF%E6%9C%AC.png

**Comment by Licoy** [comment]
不支持中文的路径图片，包含缩略图这些均不支持
