### ISSUE TITLE
标题过长显示不好看

### ISSUE THREAD

**Issue by hausen1012** [Licoy/wordpress-theme-puock#399]
如果换行缩略图会被拉宽，还是希望可以像正文那样隐藏一下
![image](https://github.com/Licoy/wordpress-theme-puock/assets/50026605/2bb4f3b8-cacb-4e0f-b420-a8dc0506d9de)

**Comment by Lvshujun0918** [comment]
![image](https://github.com/Licoy/wordpress-theme-puock/assets/41245552/c445814d-0756-40f5-a952-7ab7405a109d)
![image](https://github.com/Licoy/wordpress-theme-puock/assets/41245552/6970f979-59e0-4116-93a4-00318f205bf3)
我这边正常的

**Comment by hausen1012** [comment]
> [![image](https://private-user-images.githubusercontent.com/41245552/314423054-c445814d-0756-40f5-a952-7ab7405a109d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MjI5MTEsIm5iZiI6MTcxMDkyMjYxMSwicGF0aCI6Ii80MTI0NTU1Mi8zMTQ0MjMwNTQtYzQ0NTgxNGQtMDc1Ni00MGY1LWE5NTItN2FiNzQwNWExMDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDA4MTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3MmQzOTQ3ZDY2MDQ3NTkyNzI1ZWMzODRiZjFkMjNjOTVmMzdlYzdjMDQ4OWE2NTc3YmFmOTNjN2Y3ODI3MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WG7oMuiD732PNcFgR2Z2yeeByxam-1LUFcApVG3P2ss)](javascript:void(0)) [![image](https://private-user-images.githubusercontent.com/41245552/314423088-6970f979-59e0-4116-93a4-00318f205bf3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MjI5MTEsIm5iZiI6MTcxMDkyMjYxMSwicGF0aCI6Ii80MTI0NTU1Mi8zMTQ0MjMwODgtNjk3MGY5NzktNTllMC00MTE2LTkzYTQtMDAzMThmMjA1YmYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDA4MTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1ZTQ1NmFjYjExNzg1N2JhNzdmNzg3ODhjOWFiY2M4OTQ2YTZkYzk1ZTU1ZmQyMjZhMTFkNWQ0YWFjMDU4ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0HifLLltEHjf0Xwlu5o4dOzjFh5oIWdrIGZeltydNl4)](javascript:void(0)) 我这边正常的

你的网站方便发我看看吗

**Comment by Lvshujun0918** [comment]
你好像已经关闭了issue
网址是[https://cszj.wang/](url)

**Comment by hausen1012** [comment]
> 你好像已经关闭了issue 网址是[https://cszj.wang/](url)

我发现确实是我的问题，所以关闭了。谢谢了老哥
