### ISSUE TITLE
没有评论ua和ip地址，实在无法装逼。。。

### ISSUE THREAD

**Issue by xiechangan123** [Licoy/wordpress-theme-puock#4]
如题，请博主速度添加

**Comment by Licoy** [comment]
后期会进行添加，另外欢迎提交PR

**Comment by mrdong916** [comment]
> 后期会进行添加，另外欢迎提交PR

由于对主题改的地方不少 就不提交PR了  增加UA这个可以参考 https://github.com/mrdong916/wordpress-theme-puock/commit/80e5351eebadb9f3e26663b2b39e2257f2900363

**Comment by zbqlbz** [comment]
> > 后期会进行添加，另外欢迎提交PR
> 
> 由于对主题改的地方不少 就不提交PR了 增加UA这个可以参考 [mrdong916@80e5351](https://github.com/mrdong916/wordpress-theme-puock/commit/80e5351eebadb9f3e26663b2b39e2257f2900363)

活捉一只bzqll

**Comment by rankment** [comment]
> > 后期会进行添加，另外欢迎提交PR
> 
> 由于对主题改的地方不少 就不提交PR了 增加UA这个可以参考 https://github.com/mrdong916/wordpress-theme-puock/commit/80e5351eebadb9f3e26663b2b39e2257f2900363

404
