### ISSUE TITLE
老大搜索按钮错位问题好像BUG依旧

### ISSUE THREAD

**Issue by syx594** [Licoy/wordpress-theme-puock#40]
老大搜索按钮错位问题好像BUG依旧

**Comment by Licoy** [comment]
请自行更新至：
https://github.com/Licoy/wordpress-theme-puock/commit/cb715469b69ea09474cc7cdfe300aa7d66fb5acd
这次提交记录，若还有问题，请提交相关截图及设备信息

**Comment by syx594** [comment]
> 请自行更新至：
> [cb71546](https://github.com/Licoy/wordpress-theme-puock/commit/cb715469b69ea09474cc7cdfe300aa7d66fb5acd)
> 这次提交记录，若还有问题，请提交相关截图及设备信息

我测试结果是这样de[https://i.loli.net/2021/01/05/gVYoABbRvMGdwkJ.jpg](url)

**Comment by Licoy** [comment]
@syx594 根据图片上来看并没有错位，设计上就是这样的，将关闭按钮置于搜索按钮框下方中央。

**Comment by syx594** [comment]
> @syx594 根据图片上来看并没有错位，设计上就是这样的，将关闭按钮置于搜索按钮框下方中央。

原来如此  谢谢老大
