### ISSUE TITLE
代码识别语言出错

### ISSUE THREAD

**Issue by gkwfhv** [Licoy/wordpress-theme-puock#401]
我复制粘贴了一些 python 代码，有时候代码高亮能准确地识别成 python 语法，但有些 Python 代码却不能识别成 python 语法
<img width="547" alt="PixPin_2024-03-25_23-40-34" src="https://github.com/Licoy/wordpress-theme-puock/assets/56984054/6d602341-c572-41cc-b2e8-7f2adc1dbb32">
<img width="653" alt="PixPin_2024-03-25_23-41-34" src="https://github.com/Licoy/wordpress-theme-puock/assets/56984054/63165e01-3c9b-4f06-999c-aa63b8e5e25d">

**Comment by Licoy** [comment]
如果是特定的语言，需要加入`language-python`之类的class，或者markdown使用
```
```python
```
这样的语法，具体参考 https://highlightjs.org/
