### ISSUE TITLE
主题全部开源吗？询问assets/dist/setting/index.js

### ISSUE THREAD

**Issue by jd82k** [Licoy/wordpress-theme-puock#403]
观察到主题assets\dist\setting下有个index.js文件（文件大小1M多），这个js是压缩的，有没有源码呀，目测可能引入了vue等其他的

**Comment by jd82k** [comment]
这个文件我没有在源码中看到是如何生成的，麻烦创作者描述一下，不然主题不能叫严格意义上的全部开源吧

**Comment by FourteenDP** [comment]
这个是打包后端的，你要修改可以直接克隆仓库自己修改

**Comment by FourteenDP** [comment]
还有此仓库遵循的是GPL3开源，请先了解一下GPL3开源哦

**Comment by jd82k** [comment]
> 这个是打包后端的，你要修改可以直接克隆仓库自己修改

您好，我克隆了仓库，但是只有dist压缩过的js，如果想修改原来js怎么修改呢，打包之前的，仓库中是没有的

**Comment by jd82k** [comment]
> 还有此仓库遵循的是GPL3开源，请先了解一下GPL3开源哦

我了解此协议，我只是没有在master仓库中找到dist/setting下面的js和css的未压缩版本的源代码

**Comment by Licoy** [comment]
后台配置框架属于外部集成的依赖，通过特定的字段属性JSON即可实现配置选项，这一块没有开放原始代码，请知悉！
