### ISSUE TITLE
关于主题登录验证码的问题

### ISSUE THREAD

**Issue by zzisbeauty** [Licoy/wordpress-theme-puock#407]
- 是否为已有功能：是/否
- 问题描述：主题不错，但是难道就没有人觉得这个主题的登录验证码非常难以输入正确？ 有时候输入了几百遍了都还在提示验证码输入错误导致难以注册与登录。 

【建议】

- 建议1：如果可以，优化这个验证码的方式，换成滑动或者改成一个比较清晰大家容易看出来的验证码。
- 建议2：如果可以，可以在后台设置可以关闭注册或者登录时使用的验证码

**大家都是小破站，没必要把验证码设计的这么难输入正确，看都看不清的验证码。**

**Comment by Lvshujun0918** [comment]
![image](https://github.com/Licoy/wordpress-theme-puock/assets/41245552/4e178ded-a250-4628-86df-ce309fb10dd5)
自己去申请一个极验验证码即可。关于关闭验证码，我之后再提PR

**Comment by hotchestnut0** [comment]
这似乎是一个bug，inc/php-captcha.php的第140行
$this->text = strtolower(implode('',$code));把验证码全部转换成了小写，但是生成的验证码图片却仍然包含大写，所以无论怎么输入都不正确。我的临时解决方案是把strtolower函数去掉，或者删除characters中的所有大写字母。

**Comment by zzisbeauty** [comment]
> 这似乎是一个bug，inc/php-captcha.php的第140行 $this->text = strtolower(implode('',$code));把验证码全部转换成了小写，但是生成的验证码图片却仍然包含大写，所以无论怎么输入都不正确。我的临时解决方案是把strtolower函数去掉，或者删除characters中的所有大写字母。

晚上回家试试

**Comment by Licoy** [comment]
> 这似乎是一个bug，inc/php-captcha.php的第140行 $this->text = strtolower(implode('',$code));把验证码全部转换成了小写，但是生成的验证码图片却仍然包含大写，所以无论怎么输入都不正确。我的临时解决方案是把strtolower函数去掉，或者删除characters中的所有大写字母。

这里存储的是小写，用户输入的数据进行验证也是会转成小写，就是为了不区分大小写，你这是背道而驰呀

**Comment by hotchestnut0** [comment]
> > 这似乎是一个bug，inc/php-captcha.php的第140行 $this->text = strtolower(implode('',$code));把验证码全部转换成了小写，但是生成的验证码图片却仍然包含大写，所以无论怎么输入都不正确。我的临时解决方案是把strtolower函数去掉，或者删除characters中的所有大写字母。
> 
> 这里存储的是小写，用户输入的数据进行验证也是会转成小写，就是为了不区分大小写，你这是背道而驰呀

我的水平有限，也不熟悉php。但是如果不对CaptchaBuilder的create方法做上述修改的话，哪怕图片显示A334这样的显而易见的验证码都无法通过，必须要写成a334才行。我查看了pk_front_login_exec等函数的代码，没有找到将用户输入也转成小写的代码，也许是我有所遗漏或水平不足。不管怎样，我也希望能添加一个关闭验证码的选项。

**Comment by zzisbeauty** [comment]
> > > 这似乎是一个bug，inc/php-captcha.php的第140行 $this->text = strtolower(implode('',$code));把验证码全部转换成了小写，但是生成的验证码图片却仍然包含大写，所以无论怎么输入都不正确。我的临时解决方案是把strtolower函数去掉，或者删除characters中的所有大写字母。
> > 
> > 
> > 这里存储的是小写，用户输入的数据进行验证也是会转成小写，就是为了不区分大小写，你这是背道而驰呀
> 
> 感谢回复。我的水平有限，也不熟悉php。但是如果不对CaptchaBuilder的create方法做上述修改的话，哪怕图片显示A334这样的显而易见的验证码都无法通过，必须要写成a334才行。我查看了pk_front_login_exec等函数的代码，没有找到将用户输入也转成小写的代码，也许是我有所遗漏或水平不足。不管怎样，我也希望能添加一个关闭验证码的选项。

其实最好的方案是改成简单一个滑块拉到最右的验证码。 方便还有效。

**Comment by Lvshujun0918** [comment]
我在我的[Puock修改版](https://github.com/Lvshujun0918/Puock-NG)中已经改进了这个问题，但是由于composer处理太麻烦，我暂时就不提PR合并进这个项目里了。 @Licoy 如果有空可以参考一下。

**Comment by zzisbeauty** [comment]
> 我在我的[Puock修改版](https://github.com/Lvshujun0918/Puock-NG)中已经改进了这个问题，但是由于composer处理太麻烦，我暂时就不提PR合并进这个项目里了。 @Licoy 如果有空可以参考一下。

大佬你在NG项目已经修改了验证码吗？ 如果是的话，我可以更新现有的主题吗？ 会有报错吗？

**Comment by Lvshujun0918** [comment]
> > 我在我的[Puock修改版](https://github.com/Lvshujun0918/Puock-NG)中已经改进了这个问题，但是由于composer处理太麻烦，我暂时就不提PR合并进这个项目里了。 @Licoy 如果有空可以参考一下。
> 
> 大佬你在NG项目已经修改了验证码吗？ 如果是的话，我可以用NG的代码替换更新现有的主题吗？ 会有报错吗？原始的主题设置会保留下来吗？

按照道理应该是不会有报错，配置方面，可以用导入导出功能导入一下，你可以先试试看，保留原主题方便切换回去。有什么问题可以联系我。
![image](https://github.com/Licoy/wordpress-theme-puock/assets/41245552/53f6749b-e861-499f-bb50-d8adfc3e7768)

**Comment by zzisbeauty** [comment]
> > > 我在我的[Puock修改版](https://github.com/Lvshujun0918/Puock-NG)中已经改进了这个问题，但是由于composer处理太麻烦，我暂时就不提PR合并进这个项目里了。 @Licoy 如果有空可以参考一下。
> > 
> > 
> > 大佬你在NG项目已经修改了验证码吗？ 如果是的话，我可以用NG的代码替换更新现有的主题吗？ 会有报错吗？原始的主题设置会保留下来吗？
> 
> 按照道理应该是不会有报错，配置方面，可以用导入导出功能导入一下，你可以先试试看，保留原主题方便切换回去。有什么问题可以联系我。 ![image](https://private-user-images.githubusercontent.com/41245552/325479402-53f6749b-e861-499f-bb50-d8adfc3e7768.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxOTA3ODIsIm5iZiI6MTcxNDE5MDQ4MiwicGF0aCI6Ii80MTI0NTU1Mi8zMjU0Nzk0MDItNTNmNjc0OWItZTg2MS00OTlmLWJiNTAtZDhhZGZjM2U3NzY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI3VDA0MDEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwYzk4YjM2ZmJjYzMxMTk4MWYyZjI1NTFkM2JjOGE1ODFmMmFkMTQyZGZjNDM5MmYzNDc2Mzc4NTYwNzZhYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.caClu7PgMSoPVOwIgITMO1TpiZghFxtH_Mitmj3z4Jc)

测了：
- 如果原站已经设置好，替换为NG版本会导致站点失效，原站就乱了。
- 如果时新站，直接使用NG，那个将会没有问题，NG可以正常设置，新站也可正常显示。

建议：
- 已经基于官方主题搭建好网站的人，就不要用NG了
- 新站直接用NG，但是NG的验证码好像是严格区分大小的。好像是这样。
- 都不用，等主题作者 @Lvshujun0918 更新新版的优化验证码后的主题。



感谢原版作者的工作，感谢 @Licoy 的工作。
希望帮助到后来人。

**Comment by Lvshujun0918** [comment]
替换版本导致站点失效，样式乱的问题可否提供一下你的配置，在我项目里提个issue，谢谢！ @zzisbeauty

**Comment by Lvshujun0918** [comment]
收到了，我再去查一查，感谢！

**Comment by Licoy** [comment]
v2.8.4已解决

**Comment by zzisbeauty** [comment]
> v2.8.4已解决

在 NG 主题上修复的吗？

**Comment by Lvshujun0918** [comment]
不是吧，应该是在这个主题上修复的

**Comment by zzisbeauty** [comment]
> 不是吧，应该是在这个主题上修复的

试了一下，验证码的图片风格没有变，大佬你修改的是识别的过程吗？


感谢作者的工作。
