### ISSUE TITLE
新版最新评论中存在错误！

### ISSUE THREAD

**Issue by ailcc** [Licoy/wordpress-theme-puock#411]
- 主题版本号：最新版，包括发行版
- WordPress版本：6.1.2
- PHP版本：[选填]
- 问题阐述：最新评论中存在错误，无法跳转到正确的页面。
- 源代码：<a class="puock-link" <?php pk_link_target() ?> href="<?php echo get_permalink($comment->comment_ID).'#comment-'.$comment->comment_ID ?>">
应该修改为：<a class="puock-link" <?php pk_link_target() ?> href="<?php echo get_permalink($comment->comment_post_ID).'#comment-'.$comment->comment_ID ?>">

**Comment by Lvshujun0918** [comment]
我已经提出PR，#412
