### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by Tyler913** [Licoy/wordpress-theme-puock#420]
- 主题版本号：2.8.3
- WordPress版本：6.5.2
- PHP版本：80
- 问题阐述：
![image](https://github.com/Licoy/wordpress-theme-puock/assets/74124552/993846e2-2964-45e3-814d-80a926dc0d24)
访客点击登陆按钮，登陆界面显示为这样，而且只能持续大概0.3秒，就闪一下。无法登陆

**Comment by Lvshujun0918** [comment]
恐怕是js或者css的问题，看一下控制台有没有报错
