### ISSUE TITLE
文章中插入自定义的html代码+JavaScript代码，内容无法输出

### ISSUE THREAD

**Issue by jungege2022** [Licoy/wordpress-theme-puock#424]
- 主题版本号：[v2.8.4](https://github.com/Licoy/wordpress-theme-puock/releases/tag/v2.8.4)
- WordPress版本：6.5.3 版本
- PHP版本：[选填]
- 问题阐述：
文章中插入自定义的html代码+js脚本，html代码内容能正常输出，JavaScript代码无法执行
以下是截图：1图是代码文本输入截图，2图是可视化下的截图
![1](https://github.com/Licoy/wordpress-theme-puock/assets/132636882/b1686350-6044-4127-894d-10db7739681c)
![2](https://github.com/Licoy/wordpress-theme-puock/assets/132636882/cb584bb5-b16d-4b6b-958e-76c680397a73)

**Comment by Licoy** [comment]
你在可视化下怎么可能会运行...自己输出到页面前段查看

**Comment by jungege2022** [comment]
保存发布，到前端页面查看是空白，没有内容，我用另一个主题测试下是可以正常显示（代码没有写错）
![825EAEBB-5170-4F88-AF16-032DC190CFC0](https://github.com/Licoy/wordpress-theme-puock/assets/132636882/bd6a679b-d44d-4e11-a573-a74f678b1d9c)
![7320C403-4FE6-4618-8C36-6C594C4DE80F](https://github.com/Licoy/wordpress-theme-puock/assets/132636882/a8bcd1ca-9055-4f34-8d88-ffbe7deca6bc)
