### ISSUE TITLE
更改配置后保存时报错

### ISSUE THREAD

**Issue by i7366464** [Licoy/wordpress-theme-puock#428]
![微信截图_20240704212312](https://github.com/Licoy/wordpress-theme-puock/assets/60738903/78f5c9ff-b832-42b3-b99c-c248976ca46a)
如图所示，显示配置保存失败: [object Object]

**Comment by i7366464** [comment]
控制台里错误信息
load-scripts.php?c=0&load%5Bchunk_0%5D=jquery-core,jquery-migrate,utils,moxiejs,plupload&ver=6.5.5:2  
Mixed Content: The page at 'https://xxxxxx.com/wp-admin/admin.php?page=puock-options' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://xxxxx.com/wp-admin/admin-ajax.php?action=update_theme_options'. This request has been blocked; the content must be served over HTTPS.
查找历史issue，发现反馈关闭CF的cdn可以保存成功，尝试过后，依旧保存失败。

**Comment by Licoy** [comment]
这是wordpress将你的https的链接渲染成为http，重新保存固定链接即可
