### ISSUE TITLE
自定义主题界面报错

### ISSUE THREAD

**Issue by HEW666** [Licoy/wordpress-theme-puock#429]
- 主题版本号：2.8.4
- WordPress版本：6.5.5
- PHP版本：8.0.26
- 问题阐述：Warning: Attempt to read property "term_id" on bool in /www/wwwroot/website/wp-content/themes/wordpress-theme-puock-2.8.4/inc/fun/core.php on line 693
- 报错截图：
![TinySnap-2024-07-08-17 08 32](https://github.com/Licoy/wordpress-theme-puock/assets/67474081/c1b49e77-14d0-4eb7-9b4f-dcaad8ea442d)

**Comment by Licoy** [comment]
你没有设置任何菜单
