### ISSUE TITLE
php8.0运行错误

### ISSUE THREAD

**Issue by miniwater** [Licoy/wordpress-theme-puock#43]
WordPress版本：5.6
主题版本号：1.4
PHP版本：[选填] 8.0
问题阐述：
---------------

致命错误：/www/wwwroot/www.******.com/wp-content/themes/wordpress-theme-puock-1.4/inc/fun/post-tags中不再支持带有花括号的数组和字符串偏移访问语法。第4行的php
此站点遇到了致命错误，请查看您的站点管理邮件地址来获得指引

**Comment by Licoy** [comment]
@miniwater 已修复字符串偏移访问语法，可临时将最新`post-tags.php`文件进行替换解决或等待下个版本发布：
https://github.com/Licoy/wordpress-theme-puock/blob/master/inc/fun/post-tags.php
