### ISSUE TITLE
能否增加文章按更新时间排序，让最近更新的文章排前面。

### ISSUE THREAD

**Issue by lingran10** [Licoy/wordpress-theme-puock#433]
- 是否为已有功能：否
- 建议阐述：
WordPress网站默认是按照发布时间来文章排序的，最近发布的排在前面。但是对于更新频繁的资源型网站来说，让最近更新的文章排在前面更好。

**Comment by Licoy** [comment]
https://github.com/Licoy/wordpress-theme-puock/releases/tag/v2.8.5 中已支持的功能
