### ISSUE TITLE
启用子主题后，文章随机封面图片显示不出来了

### ISSUE THREAD

**Issue by 2536629322** [Licoy/wordpress-theme-puock#434]
- 主题版本号：2.8.5
- WordPress版本：6.6.1
- PHP版本：[选填]
- 问题阐述：启用子主题后，文章随机封面图片显示不出来了，访问图片地址报错：
Warning: file_exists(): open_basedir restriction in effect. File(/wp-content/themes/puock-child/assets/img/random/5.jpg) is not within the allowed path(s): (/www/wwwroot/xxxxx/:/tmp/) in /www/wwwroot/xxxxx/wp-content/themes/wordpress-theme-puock-2.8.5/timthumb.php on line 938

Warning: file_exists(): open_basedir restriction in effect. File(/www/wwwroot/xxxxx/wp-content/themes/wordpress-theme-puock-2.8.5/timthumb.php/wp-content/themes/puock-child/assets/img/random/5.jpg) is not within the allowed path(s): (/www/wwwroot/xxxxx/:/tmp/) in /www/wwwroot/xxxxx/wp-content/themes/wordpress-theme-puock-2.8.5/timthumb.php on line 963
A TimThumb error has occured
The following error(s) occured:
Could not find the internal image you specified.

Query String : w=400&h=200&a=c&zc=1&q=90&src=http://xxxxx/wp-content/themes/puock-child/assets/img/random/5.jpg
TimThumb version : 2.8.14

**Comment by 2536629322** [comment]
![微信图片_20240819131824](https://github.com/user-attachments/assets/9414e9dc-cd99-4bd3-b4cd-46d7bcdb8827)
这样子主题就可以正常请求父主题路径了

**Comment by Licoy** [comment]
@2536629322 是的，这个确实是个优化项
