### ISSUE TITLE
「求助」：启用主题后，博客的前端页面提示：此站点遇到了致命错误。

### ISSUE THREAD

**Issue by stuffren** [Licoy/wordpress-theme-puock#440]
- 主题版本号：wordpress-theme-puock-2.8.7.zip
- WordPress版本：WordPress 6.6.1
- PHP版本：PHP 8.1.2-1ubuntu2.18 (cli) 
- 问题阐述：
安装了最新的2.8.7版本的主题，启用主题，然后到博客的前台页面，它提示：
此站点遇到了致命错误。
![01](https://github.com/user-attachments/assets/72f4091a-1b24-4682-ba92-667fcc6694a9)

等待作者的回复！！

**Comment by Licoy** [comment]
看nginx或者wp日志，开启wp的调试模式看日志，你这个截图和反馈等于1个信息都没有

**Comment by Licoy** [comment]
无回复，关闭
