### ISSUE TITLE
请问一下主题可以使用国内的公共cdn加速吗？

### ISSUE THREAD

**Issue by vbskycn** [Licoy/wordpress-theme-puock#441]
cdn.jsdelivr.net 等国外的几乎使用不了，

国内的
https://unpkg.zhimg.com
https://cdn.baomitu.com
https://cdn.bytedance.com/
知呼，字节，饿了吗 好像也会同步npm资源，作者是不是考虑也加入
网站放在 阿里云小水管，如果有cdn加载资源，那速度可以快好多

**Comment by Licoy** [comment]
你可以后台自定义，只要他们支持

**Comment by vbskycn** [comment]
就是不知道怎么传的上面，后台可选的只有国外的那几个，但是速度太慢了
国内的不知道怎么找那个有
