### ISSUE TITLE
登录按钮藏的太深了

### ISSUE THREAD

**Issue by blmbolon** [Licoy/wordpress-theme-puock#447]
- 是否为已有功能：是
- 建议阐述：
建议PC首页顶部的登录按钮改为文字，移动首页的登录也提至顶端，用户现在几乎找不到登录口，可以的话，建议做一个登录小工具直接调用；评论区域，回复可见区域，提醒登录的位置最好加上登录链接，这样用户体验更好

**Comment by Licoy** [comment]
登录就在右上角，并不深

**Comment by blmbolon** [comment]
不能把用户想的太聪明，设置回复可见，他们根本找不到登录口



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年10月25日 15:48 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [Licoy/wordpress-theme-puock] 登录按钮藏的太深了 (Issue #447) |

登录就在右上角，并不深

**Comment by hausen1012** [comment]
其实我之前也有这种感觉
