### ISSUE TITLE
设置提交百度收录时  提交文章编辑/保存会报错 

### ISSUE THREAD

**Issue by xiaoyi510** [Licoy/wordpress-theme-puock#448]
- 主题版本号：2.8.7
- WordPress版本：6.6.2
- PHP版本：8.1
- 问题阐述：

提交百度收录会报错 
:  Uncaught Error: Cannot use object of type WP_Error as array in /www/wwwroot/xx.com/wp-content/themes/wordpress-theme-puock/inc/fun/core.php:491
Stack trace:
#0 /www/wwwroot/xxx.com/wp-includes/class-wp-hook.php(326): pk_baidu_submit()
#1 /www/wwwroot/xx.com/wp-includes/class-wp-hook.php(348): WP_Hook-&gt;apply_filters()
#2 /www/wwwroot/xx.com/wp-includes/plugin.php(517): WP_Hook-&gt;do_action()
#3 /www/wwwroot/xx.com/wp-includes/post.php(5579): do_action()
#4 /www/wwwroot/xx.com/wp-includes/post.php(4781): wp_transition_post_status()
#5 /www/wwwroot/xx.com/wp-includes/post.php(4993): wp_insert_post()
#6 /www/wwwroot/xx.com/wp-admin/includes/post.php(453): wp_update_post()
#7 /www/wwwroot/xx.com/wp-admin/post.php(227): edit_post()
#8 {main}
  thrown in

**Comment by yaomou** [comment]
而你我的朋友，你是真正的英雄。我找了两天原因了难怪我一直更新报错。

**Comment by Licoy** [comment]
应该百度返回的非正常的预期值，导致json数组反序列化失败，下个版本会屏蔽该错误
