### ISSUE TITLE
使用 get_author_posts_url 函数可以得到 wordpress 后台的用户名登录凭据

### ISSUE THREAD

**Issue by Ryanjiena** [Licoy/wordpress-theme-puock#45]
WordPress版本：5.6
主题版本号：1.4
PHP版本：[选填] 7.4
问题阐述：在文章界面版权声明中使用 `get_author_posts_url` 函数获取文章作者链接，从中可以得到 wordpress 后台的用户名登录凭据。

---------------

https://github.com/Licoy/wordpress-theme-puock/blob/8fd89084281c94e2b996653874300f99107f3196/single.php#L74-L77 

在主题的文章页面的版权声明中使用 `get_author_posts_url` 函数获取文章作者链接，从中可以得到 wordpress 后台用户名登录凭据。为了网站安全，建议还是更换为 `the_author_meta( 'user_url )` 函数返回文章作者的站点链接。

**Comment by Licoy** [comment]
@Ryanjiena 可以采用`启用后台登录保护`来对登录页面加以限制访问
