### ISSUE TITLE
键盘左右键翻页功能会导致评论框的文字丢失

### ISSUE THREAD

**Issue by wangdacuicui** [Licoy/wordpress-theme-puock#451]
- 主题版本号：V2.8.7
- WordPress版本：6.6.2
- PHP版本：7.4
- 问题阐述：
- 最近刚使用了这个高颜值主题，非常喜欢，但遇到一个BUG不得不反馈下，希望官方及时修复。
- 本主题默认设置了在文章浏览页面，按键盘左右键会自动翻页（上一篇文章、下一篇文章），但是这个功能会对评论者造成极大不便。
- 当评论者在评论框输入文字时，经常会用左右键来调整修改文字，这个时候，立马就会触发自动翻页功能，导致当前页面改变，从而导致评论框的内容丢失。
- 这个BUG不单单是我自己博客（chidd.net）出现，我在官网（licoy.cn）试了下，同样会存在。
- 所以基本判定属于本主题固有的BUG。
- 真心希望官方能及时修复。目前我是采用的屏蔽键盘左右键来避免评论时不小心导致文字丢失。但这样也很影响体验感。
-

**Comment by hausen1012** [comment]
这个其实是作者给左右箭头绑定了上一篇、下一篇的事件。我认为这个事件是没必要的，因为我也经常遇到这个问题，打错字一使用键盘调整就会导致页面刷新，评论内容不见

puock.min.js 中的代码。

```js
{
        key: "keyUpHandle",
        value: function() {
            var a = $(".single-next-or-pre");
            a && (window.onkeyup = function(t) {
                var e = null;
                switch (t.key) {
                case "ArrowLeft":
                    e = a.find("a[rel='prev']").attr("href");
                    break;
                case "ArrowRight":
                    e = a.find("a[rel='next']").attr("href")
                }
                e && (window.location = e)
            }
            )
        }
    }
```

**Comment by wangdacuicui** [comment]
> 作者给左右箭头绑定了上一篇、下一篇的事件。我也同样认为这个事件是没必要的，因为我也经常遇到这个问题，打错字一使用键盘调整就会导致页面刷新，评论内容不见
> 
> puock.min.js 中的代码。
> 
> ```js
> {
>         key: "keyUpHandle",
>         value: function() {
>             var a = $(".single-next-or-pre");
>             a && (window.onkeyup = function(t) {
>                 var e = null;
>                 switch (t.key) {
>                 case "ArrowLeft":
>                     e = a.find("a[rel='prev']").attr("href");
>                     break;
>                 case "ArrowRight":
>                     e = a.find("a[rel='next']").attr("href")
>                 }
>                 e && (window.location = e)
>             }
>             )
>         }
>     }
> ```

非常感谢，删除这些代码后，完美解决问题。

**Comment by Siphompeks** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
