### ISSUE TITLE
希望增加付费阅读 会员机制

### ISSUE THREAD

**Issue by RSG2019** [Licoy/wordpress-theme-puock#455]
- 是否为已有功能：否
- 建议阐述：
我看主题是指广告位等收益，但是如果是阅读付费内容可以增加站点收益，相比广告来的更直接一些。

**Comment by Licoy** [comment]
开源版本不会增加相关付费、会员机制

**Comment by Olowojaye** [comment]
maybe this solution will solve your problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)
