### ISSUE TITLE
保存配置时提示“配置保存失败: [object Object]”

### ISSUE THREAD

**Issue by lihaoxi001** [Licoy/wordpress-theme-puock#458]
- 主题版本号：2.8.11
- WordPress版本：6.7
- PHP版本：8.0
- 问题阐述：保存配置时提示"配置保存失败: [object Object]"
- 展开的那一行是保存时弹出的信息：
![image](https://github.com/user-attachments/assets/15abe1da-f354-4fe6-aecf-9c8d5d8e9d07)

**Comment by Licoy** [comment]
https不可以请求http的xhr请求，尝试重新保存固定链接
