### ISSUE TITLE
侧边栏是否能支持关闭？

### ISSUE THREAD

**Issue by istraw** [Licoy/wordpress-theme-puock#47]
是否为已有功能：是/否
建议阐述：
---------------
目前侧边栏没有添加任何小工具，但是区域还是被占据，只能手动从代码上调整，后期是否能支持后台开启关闭？谢谢。

**Comment by Licoy** [comment]
文章和页面在编辑页面底部均有`隐藏侧边栏`的选项，不过都是针对单一的，可以考虑增加一个全局控制选项
