### ISSUE TITLE
wordpress5.6<站点健康状态>出现这些提示，不知道是否影响网站安全运行？

### ISSUE THREAD

**Issue by weweyes** [Licoy/wordpress-theme-puock#48]
WordPress版本：5.6
主题版本号：1.4
PHP版本：7.4
问题阐述：请教各位大佬，wordpress<站点健康状态>出现这些提示，不知道是否影响网站安全运行？
---------------
<img width="825" alt="Snipaste_2021-01-14_12-18-31" src="https://user-images.githubusercontent.com/59646715/104544427-ac27b800-5662-11eb-9515-7b0ccec3394c.png">

**Comment by Licoy** [comment]
@weweyes 从图中来看所示的错误和本主题没多大关系，因为本主题内（除检测更新外）暂时无任何请求第三方接口的API，所以这不是一个BUG。

猜想可能是由于您的php设置或其他插件及服务器网络原因导致的，需要您自行具体分析。
