### ISSUE TITLE
能否让页面两栏对齐固定？让页面看起来更加美观

### ISSUE THREAD

**Issue by weweyes** [Licoy/wordpress-theme-puock#49]
Licoy:能否让页面两栏对齐固定？让页面看起来更加美观

![555555](https://user-images.githubusercontent.com/59646715/104886688-1ca54080-59a5-11eb-87d3-0ce35edf6e96.jpg)

**Comment by Licoy** [comment]
@weweyes 本主题是依赖bootstrap的栅格类，正常视图下是8/4占比，如果是9/3占比的话侧边栏又太小了。
