### ISSUE TITLE
使用markdown编辑器插入代码块，显示异常问题

### ISSUE THREAD

**Issue by xbclub** [Licoy/wordpress-theme-puock#5]
插件名：WP Editor.md
编辑器插入字符串如下：
![](https://cdn.jsdelivr.net/gh/xbclub/imageCDN/upload/20200718125443.png)
显示如下:
![](https://cdn.jsdelivr.net/gh/xbclub/imageCDN/upload/20200718125752.png)

**Comment by Licoy** [comment]
这个需要排查一下，目前没有对`WP Editor.md`插件进行兼容性测试

**Comment by zhuojiawei** [comment]
不只是代码块，和一些常用的markdown语法也不支持，比如 “”>”

> test

**Comment by Eveaz** [comment]
大佬把code样式写成类似于mark和kbd的样式了，我都是直接在经典编辑器里面加了一个pre按钮。不管啥代码，写完就
pre 代码 /pre 
包裹一下。
我用原生经典编辑器用习惯了，以前用别的主题也是自己加按钮，没用过markdown编辑器。

**Comment by Arisono** [comment]
我也遇到这样的问题，很头疼

**Comment by wanyulaowang** [comment]
+1 今天用CodeMirror Blocks这个代码块插件也是显示很奇怪
