### ISSUE TITLE
最新文章如果勾选隐藏侧边栏，首页侧边栏会隐藏

### ISSUE THREAD

**Issue by o1f** [Licoy/wordpress-theme-puock#50]
WordPress版本：5.6
主题版本号：直接clone的
PHP版本：[选填]
问题阐述：最新文章如果勾选隐藏隐藏侧边栏，首页侧边栏会隐藏，其他文章无此问题
---------------
视频问题演示

https://www.awesomescreenshot.com/video/2449974?key=53c5982665636f81dc200743faa737bb

可能需要梯子

**Comment by Licoy** [comment]
@o1f 经过本地多次反复试验，没有成功复现你所说的情况。不过你可以检查一下`主题设置`-`基本设置`中的`关闭全局侧边栏显示`有没有勾选，如果没有勾选，可以试着勾选`关闭全局侧边栏显示`保存一遍配置，再取消勾选保存配置，看看是否还存在这个问题。

**Comment by o1f** [comment]
我又看了一下, 不是隐藏,而是排版错误挤到下面去了

![image](https://user-images.githubusercontent.com/28326356/105273163-b8b58e80-5bd5-11eb-9d09-743f0cf5e3d7.png)

如果把旧文章置顶并勾选关闭侧栏也会出现这种情况 ...

**Comment by Licoy** [comment]
@o1f 你所说的问题我在本地和线上都测试了，没有复现；这个可能需要你自行看一下HTML的DMO结构是否输出完整，包括任意可以输入HTML结构的入口，例如`文章`、`侧边栏富文本`、`菜单栏`、`全局任意广告位置`等

**Comment by Licoy** [comment]
@o1f 当我在本地新建了一个站点测试时成功复现你所说的问题，目前已经解决，您可以将最新的`core.php`同步查看是否还存在此问题。

**Comment by o1f** [comment]
哦了 

php8 分类下无文章会报错

![image](https://user-images.githubusercontent.com/28326356/105316805-58861300-5bfc-11eb-858b-4fe680e85a12.png)

**Comment by Licoy** [comment]
@o1f PHP8环境问题在持续兼容中，可以先将此issue关闭，若遇其他问题再新开issue。
