### ISSUE TITLE
能否把底部的<关于我们>和<友情链接>增加隐藏选项，不需要的时候把它们隐藏起来

### ISSUE THREAD

**Issue by spysir** [Licoy/wordpress-theme-puock#51]
能否为底部的<关于我们>和<友情链接>在后台增加隐藏选项，不需要的时候把它们隐藏起来，只保留下面两部分信息

<img width="1216" alt="puock" src="https://user-images.githubusercontent.com/59646715/106099691-1027a180-6176-11eb-8564-ea408a0b97d0.png">

**Comment by Licoy** [comment]
@weweyes 可以，后续支持功能开启/关闭
