### ISSUE TITLE
创建页面无法访问

### ISSUE THREAD

**Issue by laosandegudai** [Licoy/wordpress-theme-puock#52]
WordPress版本：5.6
主题版本号：v1.4
PHP版本：[选填]
问题阐述：
---------------
使用当前主题创建的页面，选择任何模板都会导致页面只能预览，发布前页面为  `www.com/?page_id=79`
![image](https://user-images.githubusercontent.com/17979159/106352329-291e8700-631d-11eb-8fd0-546428645c11.png)
发布后链接自动变为`www.com/.html?`导致无法访问，切换到自带的主题后，该页面的链接又变回`www.com/?page_id=79`又可以访问了。

**Comment by Licoy** [comment]
@laosandegudai 切换主题后，在`设置`-`固定链接`中将配置重新保存一下试试。

**Comment by laosandegudai** [comment]
> @laosandegudai 切换主题后，在`设置`-`固定链接`中将配置重新保存一下试试。

多谢，固定连接调整后可以使用。
