### ISSUE TITLE
建议首页、侧边组件支持指定分类

### ISSUE THREAD

**Issue by Andyfoo** [Licoy/wordpress-theme-puock#53]
是否为已有功能：是
建议阐述：建议首页cms或其它形式时列出的文章可以指定分类。
侧栏的分类、文章也支持指定分类。
现在我自己已经修改了相关功能，希望官方也支持。谢谢！
---------------

**Comment by Licoy** [comment]
@Andyfoo CMS是支持指定分类的

**Comment by Andyfoo** [comment]
> @Andyfoo CMS是支持指定分类的
这个我知道，最新列表下面两列。我说的是的最新列表，幻灯片下面。
![image](https://user-images.githubusercontent.com/864512/106570838-61b69e80-6571-11eb-88ea-d123debaf4e4.png)

![image](https://user-images.githubusercontent.com/864512/106570875-7004ba80-6571-11eb-8a58-8e29751c8d96.png)

**Comment by Licoy** [comment]
@Andyfoo 那个区域无计划考虑分类指定，否则最新的文章在首页就没有入口展示了。

**Comment by Andyfoo** [comment]
> @Andyfoo 那个区域无计划考虑分类指定，否则最新的文章在首页就没有入口展示了。

有些文章不需要在首页显示，做CMS的基本功能。
侧边栏我是这么改的
![image](https://user-images.githubusercontent.com/864512/106608612-95102200-659f-11eb-826b-4d40207c7ac9.png)

**Comment by Licoy** [comment]
@Andyfoo 有些区域可以指定分类目录，后续版本会跟进，谢谢建议。

**Comment by yuhai995** [comment]
这好像用插件可以实现，水煮鱼的

**Comment by leeo1125** [comment]
这个 附议 ，真实应用场景还是挺多的，比如我需要侧边栏加入一个热门问答板块就不行，只能是所有文章的热门排行，希望下版本加入。
