### ISSUE TITLE
能否让文章列表的标题显示两行？

### ISSUE THREAD

**Issue by yuhai995** [Licoy/wordpress-theme-puock#55]
是否为已有功能：否
建议阐述：
---------------
能否让文章列表的标题显示两行？特别是列表方式手机浏览时，才显示几个字，太短了点。

**Comment by Licoy** [comment]
主要是为了防止错位，可以移除标题h2上的`t-line-1`class去除此效果

**Comment by yuhai995** [comment]
感谢，我试下
