### ISSUE TITLE
无刷新加载和分类显示模块增加分类标题

### ISSUE THREAD

**Issue by yuhai995** [Licoy/wordpress-theme-puock#56]
是否为已有功能：否
建议阐述：
---------------
大神，cms布局最新文章模块底部能否增加“点击加载更多”或页码，cms布局分两栏显示模块能否增加分类标题且支持点击到分类，页面无刷新加载在哪里开启？网站:www.kuqutan.com

**Comment by Licoy** [comment]
- 无刷新加载在主题设置-基本设置-页面无刷新加载，勾选开启即可
- cmd布局暂不考虑在本页加载更多，若要使用页码可以采用博客布局
- 两栏分类支持显示分类标题及点击到对应分类此版本貌似出了点问题，等待修复
