### ISSUE TITLE
我这是什么情况?

### ISSUE THREAD

**Issue by caijunyi** [Licoy/wordpress-theme-puock#57]
![image](https://user-images.githubusercontent.com/23582505/110290181-6d402e00-8025-11eb-8c9b-f07254c90a40.png)
![image](https://user-images.githubusercontent.com/23582505/110290222-7b8e4a00-8025-11eb-80c3-f89a89c09182.png)

我的这个不显示分类目录名称和链接，我不知道为什么！还望指教！

**Comment by Licoy** [comment]
@caijunyi 查看最新的一个commit，手动覆盖functions.php即可

**Comment by caijunyi** [comment]
![image](https://user-images.githubusercontent.com/23582505/110294269-98794c00-802a-11eb-95ad-b99c27d0d8e3.png)
覆盖后就好了，完美解决！非常感谢，已经star
