### ISSUE TITLE
手机版导航菜单点击无效

### ISSUE THREAD

**Issue by caijunyi** [Licoy/wordpress-theme-puock#58]
WordPress版本：5.7
主题版本号：最新版
PHP版本：[选填]
问题阐述：电脑版菜单点击没问题，手机版点击无效（是我加了图标的原因？不清楚）
---------------

**Comment by caijunyi** [comment]
新页面打开  这个也无效

**Comment by Licoy** [comment]
@caijunyi 实测android和ios移动端均是可以点动的，请检查是否有其他插件或配置影响了此功能
