### ISSUE TITLE
页面固定连接会自动加入html

### ISSUE THREAD

**Issue by caijunyi** [Licoy/wordpress-theme-puock#61]
WordPress版本：5.7
主题版本号：1.5
PHP版本：[选填]
问题阐述：页面的固定链接，会在帖子链接里面加入html，我博客规则一直是按照标准的固定连接设置的，这里被写死了。

![image](https://user-images.githubusercontent.com/23582505/111268136-dd733300-8667-11eb-99ad-9d2682aec90e.png)

---------------

**Comment by Licoy** [comment]
@caijunyi 这个是wp的固定连接里设置的，请检查您的配置

**Comment by caijunyi** [comment]
> @caijunyi 这个是wp的固定连接里设置的，请检查您的配置
固定链接里面我没有添加html，（之前添加过，然后我取消了html，文章页正常，没有html，但是页面就依旧有html）

**Comment by Licoy** [comment]
@caijunyi 请查看最新提交，可手动更新对应文件即可关闭页面.html后缀

**Comment by caijunyi** [comment]
> @caijunyi 请查看最新提交，可手动更新对应文件即可关闭页面.html后缀

好的，我来看一下

**Comment by caijunyi** [comment]
还是错误，固定链接没有html了 但是访问这个页面提示错误。

**Comment by Licoy** [comment]
@caijunyi 更改之后需要重新保存一下固定链接，否则会访问错误，这个在更新代码中有提示

**Comment by caijunyi** [comment]
https://blog.qujl.com/tag.html/

更改了

![image](https://user-images.githubusercontent.com/23582505/111502955-48fcf380-8781-11eb-9233-62f1697ffbba.png)


https://blog.qujl.com/tag/

依旧错误

**Comment by Licoy** [comment]
@caijunyi 需要到`xxx.com/wp-admin/options-permalink.php`重新保存，我这边测试了多个站点均是可行的，还是不行只能看你是否有其他插件与此冲突了
