### ISSUE TITLE
wp-image-67这个class导致safari浏览器上图片无法加载，必须刷新第二遍图片才出来

### ISSUE THREAD

**Issue by lookdczar** [Licoy/wordpress-theme-puock#63]
WordPress版本：5.7
主题版本号：1.5
PHP版本：7.2
问题阐述：
---------------
wp开了dubug

安卓手机不会。。chrome不会。。但是safari会。。ios和MAC都会
```
<a href="https://XXXX.png"><img src="https://XXXX.png?x-oss-process=style%2Flarge"  alt="" width="381" height="1024" 
class="aligncenter size-large  wp-image-67" /></a>
```

最后发现是插入图片时，自动添加的这个wp-image-67 class导致的，删除就没事了，这是为啥。。

**Comment by lookdczar** [comment]
我是直接用的最新版本提交

**Comment by lookdczar** [comment]
/*# sourceMappingURL=bootstrap.min.css.map */
好奇怪，我看release版本的也有这行，我手机看你的主页就不会有问题

**Comment by lookdczar** [comment]
https://www.52pearapp.com/index.php/2021/03/17/图片/

![image](https://user-images.githubusercontent.com/4469003/111459722-08d44b80-8756-11eb-8589-4fc6b36c30c8.png)

我发现第一次的时候高度是0

**Comment by Licoy** [comment]
@lookdczar 检查一下是否安装了其他插件起冲突了

**Comment by lookdczar** [comment]
> @lookdczar 检查一下是否安装了其他插件起冲突了

我把插件全禁用了也会，换其他主题就不会了。
另外我发现，wp-image-76 这个class如果最后的数字比较小就会有问题，如果数字大就不会，比如wp-image-3498，我看你的主页里，数字都是几千

**Comment by Licoy** [comment]
@lookdczar 这个是wordpress图片库的编号，可以将那篇文章的图片删除重新上传一下，改变一下编号临时解决，具体原因暂时未知

**Comment by Licoy** [comment]
@lookdczar 但是我手动将图片class更改为`wp-image-67`及`wp-image-76`获取都没有问题，预览地址：https://licoy.cn/3397.html
>上述链接文章中的两张图片class分别是`wp-image-67`及`wp-image-76`，你可以测试一下是否成功加载
