### ISSUE TITLE
主题自带的图片灯箱功能希望添加一个控制开关

### ISSUE THREAD

**Issue by n10101** [Licoy/wordpress-theme-puock#67]
是否为已有功能：是/否
建议阐述：
---------------
这个主题真是非常厉害，就是可惜会和我的灯箱冲突，主题自带的点击图片就进入幻灯片模式，这个和我想要展示的效果不同，但又取消不了，甚是苦恼，希望可以添加一个控制开关，拜谢:-D

**Comment by Licoy** [comment]
@n10101 这个是集成到`libs.min.js`中的，可自行将依赖去除即可：
https://github.com/Licoy/wordpress-theme-puock/blob/97b3fb606937ed891652cccaf3686b7b5b0cfc03/assets/js/libs.min.js#L46
