### ISSUE TITLE
增加一个文章内容需输入密码或回复可看

### ISSUE THREAD

**Issue by gatesx** [Licoy/wordpress-theme-puock#69]
是否为已有功能：否
建议阐述：需要一个输入密码查看内容的功能，WP原带的是加密整个文章/页面，但是如果我只希望文章最后一些内容加密，就麻烦点了，这个功能实现的话作用还是有的（我主要是需要输入密码查看）

---------------

**Comment by Licoy** [comment]
@gatesx 目前主题内内置的有此功能，需通过短代码调用：
```
[password pass='']
我是内容
[/password]
```
