### ISSUE TITLE
文章底部广告内容无法显示

### ISSUE THREAD

**Issue by mrdong916** [Licoy/wordpress-theme-puock#7]
使用后台设置中的文章底部广告，发现无法显示，然后在`single.php`文件中有看到文章顶部广告内容的是引入的ad文件夹中的`page-top.php`，引入代码的是 https://github.com/Licoy/wordpress-theme-puock/blob/master/single.php#L7

```
<?php get_template_part('ad/page','top') ?>
```

但是没有发现对文章底部广告内容的引入，我想底部广告应该是`page-innerb.php`这个文件,按照文章顶部内容的引入方法引入这句代码后发现依旧无法显示

```
<?php get_template_part('ad/page','innerb') ?>
```

**Comment by mrdong916** [comment]
哦对了，不只是文章底部广告内容，还有SEO中的底部/头部流量统计代码，发布文章主动推送至百度这些都无效

**Comment by Licoy** [comment]
@mrdong916 主动推送是在发布文章时自动请求百度API，请检查你的配置是否正确，ad内容不显示问题待审查
