### ISSUE TITLE
主题中的文章目录侧边栏在移动端经常性打不开

### ISSUE THREAD

**Issue by ccgakki** [Licoy/wordpress-theme-puock#70]
是否为已有功能：是
建议阐述：
---------------
侧边栏 单击或者双击 都很难打开，尝试过alook和safari。我觉得可能是侧边栏按钮太小？应该不是边缘触控问题，同一侧的直达顶部和底部没问题。

**Comment by ccgakki** [comment]
或者是能改成那种侧边悬浮的嘛？

**Comment by Licoy** [comment]
@ccgakki 确实是会有这个问题，后续版本会跟进
