### ISSUE TITLE
自动切换模式

### ISSUE THREAD

**Issue by Qi-2007** [Licoy/wordpress-theme-puock#71]
是否为已有功能：否
建议阐述：
---------------
希望能加个到点自动切换到黑/白模式

/什么时候能有自动更新？
/什么时候提交的wordpress官方啊

**Comment by Licoy** [comment]
@Qi-2007 暂时未考虑提交到WordPress官方，自动更新也并未有考虑，但考虑支持在线更新，用户手动选择更新。
