### ISSUE TITLE
网站地图

### ISSUE THREAD

**Issue by Qi-2007** [Licoy/wordpress-theme-puock#72]
是否为已有功能：否
建议阐述：
---------------
希望SEO功能上能加个网站地图（sitemap）

**Comment by Licoy** [comment]
@Qi-2007 主题页面模板中提供了HTML版本的网站地图，如果您说的是`sitemap.xml`类型供搜索引擎作为索引的暂时没有

**Comment by qzhai** [comment]
WordPress 自带 wp-sitemap.xml
