### ISSUE TITLE
移动端两级菜单中的一级菜单无法正常打开。

### ISSUE THREAD

**Issue by Eveaz** [Licoy/wordpress-theme-puock#73]
WordPress版本：5.7.2
主题版本号：1.5
PHP版本：7.4
问题阐述：

在菜单导航栏中添加了两级菜单，在PC端是能正常打开一级和二级菜单的，当鼠标光标移动到一级菜单上的时候，能正常展开二级菜单，这两级菜单都能正常打开。
但是在移动端，点击一级菜单就只能展开这个一级菜单目录，一级菜单的地址变成了 #menu-sub-[编号]，在此一级菜单下面的的二级菜单可以正常打开。

**Comment by Licoy** [comment]
@Eveaz 拥有二级菜单的一级菜单也是有指向链接的吗

**Comment by Eveaz** [comment]
> @Eveaz 拥有二级菜单的一级菜单也是有指向链接的吗

是的，两级菜单没有父子关系。比如一级菜单是链接到about页面，二级菜单链接到友情链接页面，在PC浏览器上就都能正常打开。
在手机端，about页面就变成了：
`<a href="#menu-sub-60" data-toggle="collapse" data-ss1624618604="1" class="" aria-expanded="true"><i class="czs-hacker-l"></i> 关于我们<i class="czs-angle-down-l t-sm ml-1"></i></a>`

PC端是这样的：
`<a href="https://hostcsr.com/about.html" data-ss1624618604="1"><i class="czs-hacker-l"></i> 关于我们<i class="czs-angle-down-l t-sm ml-1"></i></a>`

**Comment by Licoy** [comment]
@Eveaz 好的，已知晓，预计下个版本修复
