### ISSUE TITLE
站点用了CDN图片不显示

### ISSUE THREAD

**Issue by qwe0099001** [Licoy/wordpress-theme-puock#75]
WordPress版本：5.7.2
主题版本号：1.6.0
PHP版本：[选填]
问题阐述：
---------------
首先很感谢作者,主题很喜欢也满足了个人需求.
现在遇到的问题是用了WPJAM的CDN功能,把图片都上传进行了加速
但加速的图片不显示,搜了下issues,看到办法是加白名单,然后加了白名单也无法解决.图片依旧无法加载
白名单如下
![image](https://user-images.githubusercontent.com/39852370/123262090-17d35280-d52a-11eb-8789-a9d9fb688373.png)
还有感觉这个功能能弄个可视化设置更好,能更好的面向大众.
再次感谢大佬.

**Comment by Licoy** [comment]
@qwe0099001 因为缩略图是直接访问这个文件进行加载，所以配置不好读取，另外图片还是无法加载请发一下你的控制台的错误信息

**Comment by qwe0099001** [comment]
哪里的控制台呀大佬，看了开发者的抓包工具，链接是没有报错的，响应200，但是图片打开是
![image](https://user-images.githubusercontent.com/39852370/123390756-d8f6d880-d5cd-11eb-9a36-224506f0612a.png)
这样的，一个白点。列表是这样显示的
![image](https://user-images.githubusercontent.com/39852370/123391122-4571d780-d5ce-11eb-91a5-fcd7e8a232f2.png)

**Comment by qwe0099001** [comment]
@Licoy 大佬,权限我看了都是755,应该没问题吧,尝试设置成777也一样,您这缩略图是啥机制呢?用了好几个主题也不会这样,图片的链接是https://www.xxxx.top/wp-content/themes/wordpress-theme-puock-1.6/timthumb.php?w=400&h=200&a=&zc=1&src=https://cdn.xxxx.top/wp-content/uploads/2020/06/Cache_78136cbd631718ca..jpg.
最后的参数src是我上传到阿里云的图片地址
最后大佬有QQ嘛,可以给大佬加个鸡腿求解决

**Comment by qwe0099001** [comment]
- -重装后添加白名单解决了.感谢大佬,外以后升级主题的话,又要手动添加白名单吧

**Comment by Licoy** [comment]
@qwe0099001 只要不覆盖缩略图那个php，就不用
