### ISSUE TITLE
评论关掉头像功能

### ISSUE THREAD

**Issue by qwe0099001** [Licoy/wordpress-theme-puock#76]
是否为已有功能：否
建议阐述：
---------------
在后台评论里关掉头像无效，主题一样显示头像。而且试了下头像cdn加速源都失效了，所以想关掉头像显示。
最后谢谢大佬，

**Comment by Licoy** [comment]
@qwe0099001 主题暂时没有适配wp讨论中的关闭头像显示，后续跟进

**Comment by gwkgithub** [comment]
可以下载cdn-china-yes，评论区头像就能正常显示
