### ISSUE TITLE
升级主题是整体覆盖吗？

### ISSUE THREAD

**Issue by hopewings96** [Licoy/wordpress-theme-puock#78]
我不是很懂，问一问整体覆盖之后原有的设置是不是需要重新设置，还有就是我自己修改过functions.php，覆盖升级的时候是不是需要吧新版本包里面的functions删除？

还发现一个问题就是，在后台上传安装之后是新建一个主题了，不是覆盖升级。估计和文件夹命名有关吧。

**Comment by Licoy** [comment]
@hopewings96 是的，直接上传是新主题是文件夹命名有关，建议自定义函数写入`fun-custom.php`文件内

**Comment by hopewings96** [comment]
> @hopewings96 是的，直接上传是新主题是文件夹命名有关，建议自定义函数写入`fun-custom.php`文件内

好的谢谢指导！
