### ISSUE TITLE
添加到首页面幻灯片，然后填写指定的链接，但前端表现仍然是打开本文章。

### ISSUE THREAD

**Issue by cklx0719** [Licoy/wordpress-theme-puock#80]
![image](https://user-images.githubusercontent.com/25605487/130049963-8beaf299-1402-45a1-96db-1336c4525d66.png)
指定链接后无效。

**Comment by cklx0719** [comment]
好像是改出问题来了：
1、后台新增首页幻灯前端页面无效了。就是新增了没用。我之前只设置了一个，现在设置了两个，还是只显示一个。
2、不知道为什么，进首页后再点任何页面，都没有全部加载，分类页面只显示顶部导航和底部信息，无详情内容，需要刷新一下才可以。重新点首页进去，能显示出下面的CMS分类列表，但侧边和幻灯又不显示了。也是需要重新刷新一下才可以。

**Comment by Licoy** [comment]
@cklx0719 亲测没有问题呀
