### ISSUE TITLE
大佬，可不可以增加完整显示移动端文章标题并且标题不错乱，不遮挡阅读评论数的功能。

### ISSUE THREAD

**Issue by ccgakki** [Licoy/wordpress-theme-puock#81]
是否为已有功能：否
建议阐述：
尝试删除标题h2的<h2 class="info-title t-line-1"> ，会导致移动端的标题覆盖在阅读量和评论数上面，显示错乱；
或者可以请教下如何扩展每篇文章的标题占用空间大小；另外还有是不是可以指定显示标题的字数或字体大小可以解决错乱问题。。。
---------------

**Comment by Licoy** [comment]
现在移动端都只是会显示一行，多余的会自动截断并用`...`代替

**Comment by ccgakki** [comment]
有无办法让他多显示一点，太少了标题看不明白😂

**Comment by Licoy** [comment]
@ccgakki 好的，下个版本预计支持在后台进行调控

**Comment by ccgakki** [comment]
感谢🙇‍
