### ISSUE TITLE
不支持webp缩略图

### ISSUE THREAD

**Issue by 4tstar** [Licoy/wordpress-theme-puock#83]
tim-thump 不支持 webp 图像格式
请考虑！
第三方图像 CDN 也不起作用。

**Comment by Licoy** [comment]
@4tstar 大哥issue的标题要严谨一点，webp暂不支持，后续看看有没有其他的办法，第三方图片链接要设置白名单：
https://github.com/Licoy/wordpress-theme-puock/blob/54e3a7a2bd6598f5249c294de166ea82de7806a9/timthumb.php#L132
