### ISSUE TITLE
文章摘要长度控制无效

### ISSUE THREAD

**Issue by Eveaz** [Licoy/wordpress-theme-puock#84]
WordPress版本：5.8.1
主题版本号：1.7
PHP版本：7.4
问题阐述：
---------------
编辑：抱歉，我不是很懂PHP，目前主题使用的状况是，按照主题说明，文章SEO按本主题是应该显示前250个字符；但是发布文章之后，不手动添加文章SEO描述的情况下，首页显示的当前文章摘要等于当前文章默认SEO描述，字符数均小于100个字符。所以我不清楚是哪里出了问题。

我的目的只是想让文章使用默认SEO设置，即首页文章摘要以及SEO描述显示文章前250个字符。

求解答，谢谢。

**Comment by Licoy** [comment]
现在可能是将HTML标签也算做内了
