### ISSUE TITLE
站点健康提示：session_start()函数调用生成了一个PHP会话，该会话干扰了REST API及环回请求。

### ISSUE THREAD

**Issue by itdsgithub** [Licoy/wordpress-theme-puock#85]
WordPress版本：5.8.1
主题版本号：1.7
PHP版本：[8.0]
问题阐述：
---------------
安装主题后，站点健康提示：
session_start()函数调用生成了一个PHP会话。该会话干扰了REST API及环回请求。在做出任何HTTP请求前，该会话必须由session_write_close()函数关闭。

REST API请求因遇到了错误而失败。
错误：cURL error 28: Operation timed out after 10001 milliseconds with 0 bytes received（http_request_failed）
![屏幕截图 2021-09-18 052511](https://user-images.githubusercontent.com/10280551/133855198-775bf519-7518-4e4d-a3af-b0e0202cc663.png)

-----------------------------
其实正常发文章是不影响，但是影响插件，我装webp插件时候，就没法开启，提示出错。我试过，换别的主题就不会出现这样提示了。
![2021-09-18 052704](https://user-images.githubusercontent.com/10280551/133855388-e129e1f0-3dd9-4e3d-8972-11c9b0a64238.png)
麻烦作者能看看咋回事

**Comment by Licoy** [comment]
好的，待验证后预计下个版本修复
