### ISSUE TITLE
文章摘要图片不显示文章外链

### ISSUE THREAD

**Issue by xlqywk** [Licoy/wordpress-theme-puock#86]
WordPress版本：5.8
主题版本号：1.7
PHP版本：7.0
问题阐述：文章摘要图片不显示文章外链

下面是我博客地址
https://www.aomtop.com/ 

---------------

**Comment by Licoy** [comment]
需要在这里添加白名单：
https://github.com/Licoy/wordpress-theme-puock/blob/54e3a7a2bd6598f5249c294de166ea82de7806a9/timthumb.php#L132
