### ISSUE TITLE
建议首页幻灯片可以脱离文章单独设置

### ISSUE THREAD

**Issue by sueridm** [Licoy/wordpress-theme-puock#87]
是否为已有功能：否
建议阐述：
---------------
目前咱主题的幻灯片需要在写文章处随文章设置，建议首页幻灯片可以脱离文章，进行单独设置。
这样子在中秋国庆春节之类的节日可以设置单独展示节日的海报庆祝图片。

**Comment by cklx0719** [comment]
是的，现在要在文章里设置，有个问题就是图片下方会显示出这篇文章的标题。
如果单独设置，则图片、链接、文字都是可以自定义的。
