### ISSUE TITLE
防刷验证无法正常使用

### ISSUE THREAD

**Issue by dongyao8** [Licoy/wordpress-theme-puock#89]
WordPress版本：5.8.2
主题版本号：1.8
PHP版本：7.3
问题阐述：
防刷验证API地址怎么填写呢，文档里面的地址好像是个变量，默认的配置下，评论发不出去，提示报错。只能关闭防刷验证才能正常评论。
---------------

**Comment by Licoy** [comment]
```
Vaptcha-API: http://0.vaptcha.com/verify
```
@dongyao8
