### ISSUE TITLE
底部页脚

### ISSUE THREAD

**Issue by anaivez** [Licoy/wordpress-theme-puock#91]
我看支持html标签我使用了a标签但是无效直接显示的文本
<p>< a href="http://beian.miit.gov.cn">备案说明</ a></p>

**Comment by Licoy** [comment]
你的这个html标签有问题吧，都没有闭合，试试完整的呢
```html
<a href="http://beian.miit.gov.cn">备案说明</a>
```

**Comment by anaivez** [comment]
> 你的这个html标签有问题吧，都没有闭合，试试完整的呢
> 
> ```
> <a href="http://beian.miit.gov.cn">备案说明</a>
> ```

我没复制全 我用<a href="http://beian.miit.gov.cn">备案说明</a>这个是没有用的
但是我在两边加上<p>标签就有作用了

**Comment by anaivez** [comment]
> > 你的这个html标签有问题吧，都没有闭合，试试完整的呢
> > ```
> > <a href="http://beian.miit.gov.cn">备案说明</a>
> > ```
> 
> 我没复制全 我用[备案说明](http://beian.miit.gov.cn)这个是没有用的 但是我在两边加上
> 
> 标签就有作用了

`<a href="http://beian.miit.gov.cn">备案说明</a>`

**Comment by anaivez** [comment]
> > > 你的这个html标签有问题吧，都没有闭合，试试完整的呢
> > > ```
> > > <a href="http://beian.miit.gov.cn">备案说明</a>
> > > ```
> > 
> > 
> > 我没复制全 我用[备案说明](http://beian.miit.gov.cn)这个是没有用的 但是我在两边加上
> > 标签就有作用了
> 
> `<a href="http://beian.miit.gov.cn">备案说明</a>`

p标签

**Comment by Licoy** [comment]
@anaivez 所以现在是好了对吧

**Comment by anaivez** [comment]
@Licoy 可以了
